### ISSUE TITLE
Static Analyzer Warnings

### ISSUE THREAD

**Issue by gonzalonunez** [ParsePlatform/Parse-SDK-iOS-OSX#121]
I ran it through the static analyzer and some stuff came up. Thoughts?

<img width="553" alt="screen shot 2015-08-27 at 4 48 22 pm" src="https://cloud.githubusercontent.com/assets/6403910/9532743/7cdb375c-4cdb-11e5-8a73-7a5a9350b183.png">

The first one is probably a compiler blip since remoteOperationSet is originally initialized as nil. The line in question is line 1116 of PFObject.m. 

The rest are just some coding convention issues with any methods that accept NSError** as a parameter and have a void return value. See:

<img width="919" alt="screen shot 2015-08-27 at 4 53 11 pm" src="https://cloud.githubusercontent.com/assets/6403910/9532862/2c995930-4cdc-11e5-9c69-24d8990fd398.png">

Is this anything worth fixing? I'd like to hear your guys' thoughts on this before going ahead and rewriting some stuff.

**Comment by nlutsenko** [comment]
Hey @gonzalonunez, thanks for running this, you are right - we should be a better resident here.
Feel free to change `fetch`/`refresh` to return `self` there (an `instancetype`), since the completion block of `fetchInBackground` has a PFObject.

You can actually simply convert those methods to return something like this:
```objc
- (instancetype)fetch:(NSError **)error {
    return [[self fetchInBackground] waitForResult:error];
}
```

Looking forward to seeing the PR. :grin:

**Comment by gonzalonunez** [comment]
@nlutsenko just submitted #122

**Comment by richardjrossiii** [comment]
@gonzalonunez Just FYI, we get emails for every PR that is sent, no need to ping on the issue for it :)

**Comment by gonzalonunez** [comment]
Whoops, sorry about that!
