### ISSUE TITLE
PFTwitterUtils.logInWithBlock Issue

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/Parse-SDK-iOS-OSX#127]
Hi guys, 

Here is how my app is setup. I have a UITabBarViewController which presents a modal ViewController for registration. This is where my action for login is. It works fine when a user doesn't have twitter accounts on his device, they are presented with login in a popup with webview. 

When there are accounts on device I get the following error: 
Warning: Attempt to present <UIAlertController: 0x1610dc380> on <Design_Hunt.UITabBarViewController: 0x15fe4c880> whose view is not in the window hierarchy!

How can I force it to present UIAlertController in my ViewController? 

FYI, this is iOS 9 and latest Parse SDK.

Thanks.

**Comment by nlutsenko** [comment]
Hey @talkaboutdesign, any chance you can share your view controller hierarchy here.
We are trying to present UIAlertController onto the topmost view controller, but I think it fails to do so for your view controller hierarchy, that's why seeing the view controller hierarchy would help us support it.

**Comment by talkaboutdesign** [comment]
This looks like its fixed with the latest PFTwitterUtils framework. However I think a much better experience would be to present it as an action sheet instead of regular alert. 

![img_0881](https://cloud.githubusercontent.com/assets/2926534/9553299/0d0e62e4-4d8c-11e5-9044-5aa2c6441be6.PNG)

**Comment by nlutsenko** [comment]
Yay! There indeed was a fix in #80.
Presenting inside `UIActionSheet` instead of alert - true, that is sometimes a better experience, the problem is that on iPad presentation of UIActionSheet is usually coming from a rect in a form of popover, which makes the API messy in that case.

Would love to discuss further or even to review a Pull Request on this though.
