### ISSUE TITLE
Is App Version supposed to be the build number?

### ISSUE THREAD

**Issue by simonsez** [ParsePlatform/Parse-SDK-iOS-OSX#163]
I'm new to Parse, and I just did a test that didn't work as I expected it so I thought I'd ask. My use case was I have an App with versions 1.0 and 1.1, and at some point I might want to push to those old versions specifically. In the push dashboard I selected version 1.1 and it said no one had those versions, and I realized that the "App Version" in the dashboard actually corresponds to the build number:

````
- (void)_updateVersionInfoFromDevice {
    NSDictionary *appInfo = [[NSBundle mainBundle] infoDictionary];
    NSString *appName = appInfo[(__bridge NSString *)kCFBundleNameKey];
    NSString *appVersion = appInfo[(__bridge NSString *)kCFBundleVersionKey];
    NSString *appIdentifier = appInfo[(__bridge NSString *)kCFBundleIdentifierKey];
   ....
}
```

**kCFBundleVersionKey** [maps](http://stackoverflow.com/a/7608711) to the build number, while **CFBundleShortVersionString** maps to the version number, which I suspect is the one most business folks would know (presumably they are sending the pushes).

Is that the intended behavior?

**Comment by nlutsenko** [comment]
It is indeed an intended behavior. 
The logic is quite simple, actually:
`CFBundleVersion` specifies the build version number of the bundle, which identifies an iteration (released or unreleased) of the bundle.
`CFBundleShortVersionString` specifies a human-readable, publicly accessible (this is what your users see in the App Store) version of the application.
This all translates to a simple fact that for any given version of the app that is going to ship - you can have multiple builds of the application that you are testing (this is what Apple does, actually), e.g. they have `9.0` as CFBundleShortVersionString, while `CFBundleVersion` is a hex number that uniquely identifies a build.

I think there are 2 things you can do to fix the problem on your end:
- Use the same string for both `CFBundleVersion` and `CFBundleShortVersionString`, since those values are strings and are not enforced to say be numbers (less optimal)
- Use push audiences (pre-built and saved) in Push Console that have a query set to `appVersion is any of `[100, 101, 102]` of the application if you want to target version 1.1 and not 1.2

I hope this helps.

**Comment by nlutsenko** [comment]
![screen shot 2015-09-02 at 6 53 13 pm](https://cloud.githubusercontent.com/assets/606991/9649021/eef88516-51a3-11e5-92dc-5cd902194af0.png)
Here is a screenshot of the Create Audience dialog in Push Console showing what I meant in the second approach.

**Comment by simonsez** [comment]
Thank you for the explanation, and while I understand the reasoning in the two values, I'm not sure I see the business cases for actually wanting to push to the non-human readable version. When (other than development) would you use those build values?

Nevertheless thank you for confirming that it's working as intended, I just might recommend that you update the documentation - I think it's confusing that **appVersion** maps to **build number**. 

Thanks again!

**Comment by nlutsenko** [comment]
Good point. I'll try to address that in docs.
Pull Requests for them are also very very helpful, since they give exposure to your opinion and our Docs are opensource and available [here](https://github.com/ParsePlatform/Docs)
