### ISSUE TITLE
Swift compiler runs into a segmentation fault on cocoapods v. 1.8.3

### ISSUE THREAD

**Issue by McKiernan** [ParsePlatform/Parse-SDK-iOS-OSX#264]
Xcodes swift compiler runs into a segmentation fault on both Xcode 7 GM, and Xcode 7.1 beta, having added Parse and ParseFacebookUtilsV4 through cocoapods both with version 1.8.3
Version 1.8.2 works fine.

This bug is fully reproducible and it seems to be related to the PFQuery.findObjectsInBackground method call, part of the error message is:
" While type-checking expression at [/path/UserLoader.swift:38:9 - line:51:9] RangeText="userQuery.findObjectsInBackgroundWithBlock { ( users : [AnyObject]?, error : NSError?) -> Void in "

It seems that between the versions 1.8.2 and 1.8.3 the PFQueryArrayResultBlock changed the signature to:
([PFObject]?, NSError?) -> Void in
            //code
 }

**Comment by nlutsenko** [comment]
Hey @McKiernan, it's a silly Xcode bug that should simply surface as an error.
The new method signature is 
`... findObjectsInBackgroundWithBlock { ( users : [PFObject]?, error : NSError?) -> Void in ...`
aka simply replace AnyObject with PFObject. It should fix the problem for you.
Since 1.8.3 is fully compatible with Swift 2 - we were able to provide more guarantees and expand generic types.

Let me know if there is anything else I can help you with.
