### ISSUE TITLE
Parse 1.8.5 throws deprecation warning on iOS 9

### ISSUE THREAD

**Issue by orangecoding** [ParsePlatform/Parse-SDK-iOS-OSX#284]
This warning is being thrown on iOS 9, XCode 7 and Swift 2.

'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).

**Comment by nlutsenko** [comment]
Yup, that sounds about right...
We should definitely convert to the new one, the old one will still work and appears to be not deprecated if your compatibility target is lower than iOS 9 (OS X 10.11), but since we support iOS 7.0+ (10.9+) and these methods are available there - we should use the new NSString APIs.

Marking as enhancement. Thanks for the report!

**Comment by rathodsamir** [comment]
I am also getting this error in   XCode 7.2.1 and IOS 9.2
1)  .../Source/OAuth2/GTMOAuth2Authentication.m:1207:18: 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in OS X 10.11 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).

and 

2) .../Source/OAuth2/GTMOAuth2Authentication.m:1251:29: 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in OS X 10.11 - Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding.

plz provide solution for this...

**Comment by nlutsenko** [comment]
@rathodsamir, this is absolutely not related to us, since this looks like an implementation of `GTMOAuth2Authentication`, specifically `GTMOAuth2Authentication.m` file.
