### ISSUE TITLE
.edu mailbox can't receive "verify user emails" email from parse.

### ISSUE THREAD

**Issue by EricRen20** [ParsePlatform/Parse-SDK-iOS-OSX#303]
I enabled "Verify user emails" function from the setting, but I found that users are not able to receive the email when users sign up. The function which will be called after user click signup buttion is "
   signUpInBackgroundWithBlock". There was no problem before. I don't know where is problem?

**Comment by nlutsenko** [comment]
Hey @EricRen20, thanks for the report.
Let us know if there is anything we can help you with on the client side, but as `bot` mentioned - this looks to be purely related to backend, since we are not sending emails from the client.
I am going to close this issue, feel free to reopen if there is something that I've missed.

**Comment by EricRen20** [comment]
Yeah. this is a backend issue. Thanks guys.
