### ISSUE TITLE
Build fail not found ParseTwitterUtils

### ISSUE THREAD

**Issue by smitjb45** [ParsePlatform/Parse-SDK-iOS-OSX#337]
Hello, 

I'm getting this error when using v1.8.5 on xcode7, iOS9.

ld: framework not found ParseTwitterUtils
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nlutsenko** [comment]
That means that you probably didn't add ParseTwitterUtils to linked binaries list.

ParseTwitterUtils is available from the SDK download package [here](https://parse.com/docs/downloads)  or I would also suggest starting to use Cocoapods for all your dependency management, since it simplifies the process.

Let me know if it helps.

**Comment by smitjb45** [comment]
Hello again,

I'm a little confused... is that different than adding it in Xcode? In Xcode,  ParseTwitterUtils is in linked framework and libraries. It's also in embedded binaries.

**Comment by smitjb45** [comment]
Also, everything was working till the upgrade to Xcode7 and iOS9.

**Comment by nlutsenko** [comment]
Not sure how this is related to Xcode 7, since it should have warned you the previous time as well.
Adding ParseTwitterUtils inside Xcode - yes, that's exactly what you are looking for.

I would suggest trying to delete it, re-download the latest SDK and integrate it once again.

**Comment by smitjb45** [comment]
I just noticed when I upgraded to Xcode 7 from 6, that Xcode could not find Parse, but it could find the Facebook SDK. So I looked at framework search paths and Parses SDK path was not there, so I added it. Once I added it, Xcode could find all the packages except ParseTwitterUtils. I've re-downloaded Parse SDK and added it to my project and I'm getting the same error.

**Comment by smitjb45** [comment]
Sorry, I got it fixed I think. When I re-downloaded the package it was in a different place.

**Comment by nlutsenko** [comment]
That error explicitly means that it can't find the framework to link with.
I am not sure of the best way to help you resolve this...

I've noticed a change in some automation in Xcode 7, might be related.
Instead of drag'n'dropping the framework from the downloaded location - try copying the framework over to the folder where your projects .xcodeproj is located and readding from that location.

**Comment by nlutsenko** [comment]
Great! Glad you find the solution!
^ previous post is a race condition in posting :grin:

**Comment by nlutsenko** [comment]
Going to close out the issue, as it seems everything works now :smile: 
Let me know if I could be of any more help.

**Comment by smitjb45** [comment]
Hello, Sorry I'm still having a problem with ParseTwitterUtils. On line 32 in ParseTwitterUtils.h, its giving me an error expected ')' for + (PF_NULLABLE FBSession *)session;. I'm getting the same error on lines 101, 110, 409, and 426.
