### ISSUE TITLE
Remove pinned objects in Parse iOS SDK

### ISSUE THREAD

**Issue by PSIPhone** [ParsePlatform/Parse-SDK-iOS-OSX#340]
Hi,

I was running into long pin time issue hence i decided to clear LDS by unpinning all pinned objects.
But it's not working, it does not clear data.

+(void)removeCachedforOrderandTransactionswithSkip:(int)skip withQuery:(PFQuery*)query withkey:(NSString *)key withBlock:(onSuccess)block{
    [query setSkip:skip];
    [query setLimit:MAXROWS];
    [query fromLocalDatastore];
    [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
        if (!error) {
            for (PFObject *obj in objects) {
                [PFObject unpinAllObjectsInBackgroundWithName:[obj objectForKey:key]];
            }
            if(objects.count>=MAXROWS){
                [self removeCachedforOrderandTransactionswithSkip:MAXROWS withQuery:query withkey:key withBlock:block];
            }
            else
                block(nil,nil);
        }
    }];
}
Thanks
Aamir

**Comment by nlutsenko** [comment]
Hey @PSIPhone.

The code above won't clear anything in Local Datastore (unless you have collisions between pin names and fields in your objects).
According to the documentation - `unpinAllObjectsInBackgroundWithName:` will asynchronously remove all objects with the specified pin name from Local Datastore.

`pin name` is the important piece here, where you can pin objects to multiple pins in Local Datastore, thus creating different relationships/references to the same object.

In order to remove objects from Local Datastore (unpin them), I recommend looking at the way you `pin` them in the first place.
- If it's through `pin` or `pinInBackground` (basically anything that doens't have `name` parameter) - then you are looking for `unpinAllObjectsInBackground` which unpins the objects with the default pin name.
- If you are using different pin names - the objects are going to be completely removed from Local Datastore if there are no pins referencing them.

I hope all of this makes sense and helps. Let me know if you have questions.

**Comment by PSIPhone** [comment]
Okay i just changed it works fine, now i Just [object pinInBackground] rather pinWithName:

Just one favour which is the optimum method pinningwithlabel or pinInBackground. What you just for speed.

**Comment by nlutsenko** [comment]
I would recommend using `pinInBackgroundWithName` and split data into multiple pins, depending on where you want to show the data, say split based on ViewController where you present it, or split based on how frequently you need the data.

There is a good chance that you don't need more than couple hundred (or even less) objects at any given time. This also confirms to lazy-loading pattern (we are still building for devices with limited amount of CPU/RAM), which means that you don't load more objects (from Local Datastore or over the network) than you need + a little bit more for caching.

**Comment by PSIPhone** [comment]
How can i split pinning process can you please assist. When we go for saving data in persistent storage then we use it as follows.

            PFObject* object = [PFObject objectWithClassName:@"customer"];
            [object setObject:[NSDate date] forKey:@"date"];
            [object setObject:name forKey:@"name"];         
            [object setObject:address forKey:@"address"];
            [object setObject:phone forKey:@"phone"];
            [object setObject:note forKey:@"note"];
            [object saveEventually];
            [object pinInBackgroundWithName:customerID];
