### ISSUE TITLE
Update data of non current user

### ISSUE THREAD

**Issue by chlebta** [ParsePlatform/Parse-SDK-iOS-OSX#350]
Is there any way to save data, and update data,  for non connected PFUser without using ParseCloud, from iOS device.

I'm trying to update following and followers Array in PFUser in this way 
```
 [_currentUser removeObject:_publicUser forKey:@"following"];
        [_currentUser saveInBackground];
        [_publicUser removeObject:_currentUser forKey:@"followers"];
        [_publicUser saveInBackground];
```
Where ** _currentUser = [PFUser currentUser]** and **_publicUser = nonConnectedUserToUpdate** but this doesn't update anything for both _currentUser and _publicUser

**Comment by richardjrossiii** [comment]
Sorry for taking so long to get back to you! This issue sort of fell through the cracks :grimacing:.

If you modify the ACL of the public user while signed into that account you *should* be able to update fields on it.

If not, you can always create a more traditional [join table](https://en.wikipedia.org/wiki/Junction_table) between the users, whose' ACLs are modifiable from all related users.

Hopefully this helps!

**Comment by chlebta** [comment]
Not for signed user only but for others user, For example if I want to delete a follower then I've to deleted from my **Followers table** and also delete my pointer in **Following table** of that user.
Do you get the point ?

**Comment by nlutsenko** [comment]
There are 2 things that come to my mind, which still are going to be secure in this case:
- Write a custom cloud function and use master key in cloud code to update both users, then simply return your user from that function, which in case of using Local Datastore will automatically update and persist your object locally
- Use a join table aka separate class specifically for mutual connections between users, where ACL on every row of that class would be limited to only your user for `write`, but would be `read` for the other user.

The join table solution would be somewhat harder to implement, but I recommend it over the first approach, since it's more secure, flexible, as well as you will be able to add some custom metadata, like attaching a timestamp to every follow.

**Comment by nlutsenko** [comment]
The second option (join table) will also give you a flexibility in loading list of users that follow you, which is going to conform better to lazy-loading pattern (you are using it, right? :grin:).
Also - it's worth noting that there is a fixed limitation on the size of every column on Parse Objects, meaning that taking you current approach you have a finite number of `followers` and `following`, whilst with the join table - that size would be limited by only overall size of your database.

**Comment by chlebta** [comment]
@nlutsenko for the moment I'm using something very similar to your second solution. 
I've thought about migrating my **followers and followings column** into _User table to make access and update more faster and easy to those columns, but it's seem like bad idea.
Thank's for your help

**Comment by nlutsenko** [comment]
Happy to help!
