### ISSUE TITLE
Bolts.framework issue

### ISSUE THREAD

**Issue by wangdayewjf** [ParsePlatform/Parse-SDK-iOS-OSX#361]
parseStarterproject is not have Bolts.framework

**Comment by nlutsenko** [comment]
Hey @wangdayewjf, any chance you can point to which one of the 3 possible references to parse starter project you are referencing here.
- Package downloaded from https://parse.com/docs/downloads (double checked, it explicitly includes Bolts.framework)
- Package downloaded from the releases on this repository (double checked, it explicitly includes Bolts.framework)
- To the ParseStarterProject.xcodeproj in source of this repo?

The latter one could be built by using `Parse.xcworkspace`. Since we are building from source - there is no need of having Bolts.framework, as it will be compiled from scratch and cross-referenced.
