### ISSUE TITLE
Parse Crash Reporting run script failing randomly (Xcode 7 and Parse 1.8.5)

### ISSUE THREAD

**Issue by SolomonRajput1** [ParsePlatform/Parse-SDK-iOS-OSX#362]
After I added Parse Crash Reporting my app randomly fails to build sometimes with this error: 

<i>Uploading iOS symbol files...
<i>the service is currently unavailable
<i>Command /bin/sh failed with exit code 1

This has happened many times, and once I saw this error message show up for at least 4 hours straight. Please let me know what the issue could be.

However, what I'm most concerned about is if this will affect my app in production. I imagine that this run script only runs once, when I build the app so that the symbol files can be uploaded to Parse. Even if the "service is unavailable" later on, since this run script is just for uploading the files before the app goes into production, it won't affect my end users right? I just really don't want the app to randomly terminate or not launch for my end users because of this.

EDIT: Also sometimes a stacktrace is provided, but often one is not.

**Comment by SolomonRajput1** [comment]
Hello! Just wondering if you guys have any insight into this. I have to submit my app in the next day or two so it's really important to know if this issue will affect my end users. 

Thanks!
Salman

**Comment by nlutsenko** [comment]
Hey @SolomonRajput1, thanks for the report.
Since the script is purely to upload debug symbols (which you can do at any given point of time) - you are absolutely right, this shouldn't affect your end users.

If (for any reason) the script fails to upload symbols - you can always retry, even after you submitted your app to the store.

In terms of actually getting to the error - I would recommend filing a report through FB Bug Tool (we are still using it for outages/backend issues), since this looks like a transient outage on the backend.

Let me know if there is anything I can help you with, in the meantime.
