### ISSUE TITLE
Parse anonymous user does not persist when session expires

### ISSUE THREAD

**Issue by bvallelunga** [ParsePlatform/Parse-SDK-iOS-OSX#363]
My ios users seem to get logged out when a session ends. How do I upgrade a session?

**Comment by nlutsenko** [comment]
Hey @bvallelunga, thanks for the report.
Not sure I understand the problem here, can you describe the flow that you are seeing, with what you expect and what happens?

The sessions are automatically revoked after 1 year of inactivity, which probably is not what happens here. The only other way where a session gets revoked is when the user explicitly logs out (aka `PFUser.logOut()`.

**Comment by bvallelunga** [comment]
I found out what the problem was. The session tokens were getting rejected because they were not revokable tokens. I turned revokable tokens off in Parse and it fixed everything.

**Comment by nlutsenko** [comment]
:) Not sure if helped, but am glad you found the solution.
