### ISSUE TITLE
logInInBackgroundWithAccessToken 1.8.5 does not call block

### ISSUE THREAD

**Issue by nimrodYokee** [ParsePlatform/Parse-SDK-iOS-OSX#381]
Hi,

I have a problem with the code below.
when I run it, Facebook login goes fine. But when it calls PFFacebookUtils logInInBackgroundWithAccessToken, the block is never called.

Facebook DSK 4.6.0
Bolts 1.2.2

When I downgrade parse to 1.7.4 the same code work fine.

The code:

       FBSDKLoginManager *loginManager = [[FBSDKLoginManager alloc] init];

        [loginManager logOut];
        [loginManager logInWithReadPermissions:[self getFabeBookReadPermissionsArray]
                            fromViewController:nil
                                       handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {
            if (error || result.isCancelled) {
                if (handler) {
                    handler(NO, error);
                }
            } else {
                [PFFacebookUtils logInInBackgroundWithAccessToken:[FBSDKAccessToken currentAccessToken] block:^(PFUser *user, NSError *error){
                    if (!error && user) {
                        if (handler) {
                            handler(YES, nil);
                        }
                    }
                    else {
                        handler(NO, error);
                    }
                }];
            }
        }];

**Comment by nlutsenko** [comment]
Sounds very strange, will investigate.
Thanks for the report!

**Comment by nlutsenko** [comment]
Hey @nimrodYokee, just tested this with:
- `ParseFacebookUtilsV4` - 1.9.0
- `FBSDKCoreKit` - 4.7.0
- `FBSDKLoginKit` - 4.7.0
- `Parse` - 1.9.0

This code piece here:
```objc
FBSDKLoginManager *loginManager = [PFFacebookUtils facebookLoginManager];

    [loginManager logOut];
    [loginManager logInWithReadPermissions:@[ @"public_profile" ]
                        fromViewController:nil
                                   handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {
                                       if (error || result.isCancelled) {
                                           NSLog(@"%@ %d", error, result.isCancelled);
                                       } else {
                                           [PFFacebookUtils logInInBackgroundWithAccessToken:[FBSDKAccessToken currentAccessToken] block:^(PFUser *user, NSError *error){
                                               NSLog(@"%@ %@", user, error);
                                           }];
                                       }
                                   }];
```
Works like a charm and always presents the login UI / logs me in / cancels or errors.
I can't seem to reproduce the issue that you are seeing...

Please note that Facebook SDK changed behavior of logging in - and this code will work only when run after you have at least one key window. (sticking it in `applicationDidFinishLaunchingWithOptions` won't work reliably).

Any chance you can try the latest versions of everything (we had a fix in 1.9 that might be related to this, but I am not precisely sure)?
Otherwise - we would need a precise repro, as the code posted above doesn't reproduce an issue that you are seeing.

**Comment by nimrodYokee** [comment]
Thanks nlutsenko. It sure looks like upgrading to Parse 1.9.0 solved this issue

**Comment by nlutsenko** [comment]
Glad it helped!
