### ISSUE TITLE
App Transport on PFFile with Swift2

### ISSUE THREAD

**Issue by dlove9999** [ParsePlatform/Parse-SDK-iOS-OSX#382]
Using Xcode Version 7.0.1 (7A1001)
Parse Version 1.8.5

Receiving the following message when trying to load an image using PFFIle:

        App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure.
        Temporary exceptions can be configured via your app's Info.plist file.

All other data elements are returning from the query successfully.

I have updated Parse based on the recommendations from various recommendations from the Parse group on Google with regards to this known issue.  I have also tried adding the below entries into the info.plist just to test, but images still do not load and error message persists.

NSAppTransportSecurity
NSAllowsArbitraryLoads   True

Regards

**Comment by nlutsenko** [comment]
This is super strange, since we fully comply with App Transport Security on PFFiles on SDKs starting from 1.8.4.
Can you post a link to the file that fails for you, so we can test from two sides...

**Comment by dlove9999** [comment]
Here is the code from the page that is having the issue.   This worked fine in the old version of swift and Xcode 6.x, problem surfaced with new version of Xcode.  

Thanks!

import UIKit
import Parse

class HomePageViewController: UIViewController, UITableViewDelegate {
    
    
    @IBOutlet weak var homePageTableView: UITableView!
    
    var propertyImageView = [PFFile]()
    var propertyCity = [String]()
    var propertyPrice = [String]()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let query = PFQuery(className: "Property")
        query.orderByDescending("CreatedAt")
        query.findObjectsInBackgroundWithBlock {
            
            
            (posts: [AnyObject]?, error: NSError?) -> Void in
            
            if error == nil{
                
                for post in posts! {
                    
                    self.propertyImageView.append(post["imageFile"] as! PFFile)
                    self.propertyCity.append(post["propertyCity"] as! String)
                    self.propertyPrice.append(post["propertyPrice"] as! String)
                }
                
                
                self.homePageTableView.reloadData()
            }
            
        }
    }
    
    
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) ->Int{
        
        return propertyImageView.count
        
    }
    
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) ->UITableViewCell {
        
        let singleCell:SingleRowCell = tableView.dequeueReusableCellWithIdentifier("iSingleCell") as! SingleRowCell
        
        singleCell.propertyCity.text = propertyCity[indexPath.row]
        singleCell.propertyPrice.text = propertyPrice[indexPath.row]
        
        //images
        propertyImageView[indexPath.row].getDataInBackgroundWithBlock {
            (imageData: NSData?, error: NSError? ) -> Void in
            
            if imageData != nil {
                let image = UIImage(data: imageData!)
                singleCell.propertyImageView.image  = image
            }
        }
        
        return singleCell
        
}

**Comment by nlutsenko** [comment]
@dlove9999, thanks for the code.
Can you post a link to the file here that gives you an error?

You can access it via `url` property on the file.

What I suspect is happening here is that some of these files are quite old and are coming from `files.parse.com` domain, which doesn't have `https` enabled on it.
All new files since a long time ago are going to `files.parsetfss.com`, which is the domain you are looking for, which explicitly has the ability to serve `https` and is fully supported.


There are 2 ways we can go from here, but both require the validation first that the domain is indeed `files.parse.com` for these.
- Add these piece in your Info.plist to allow non-https downloads for files coming from `files.parse.com`:
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>files.parse.com</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
        </dict>
    </dict>
</dict>
```
- Re-upload files that match that domain name, so you don't need to change anything on the client.

Let me know if this helps.

**Comment by khoogheem** [comment]
Will the Rest API start to provide HTTPS links at some point as well, so iOS and OS X projects that may need to use the Rest API not have to instruct end users of a Framework to do the info.plist dance as well

**Comment by nlutsenko** [comment]
Not sure I got the question, sorry.
You mean the scenario when you are building a specific framework where you would need to instruct people to add keys into Info.plist?

**Comment by khoogheem** [comment]
Correct.. We have a Framework that we provide to customers.
I am currently using the rest API for access to files...The JSON comes back as:

~~~
    results =     (
                {
            bundleFile =             {
                "__type" = File;
                name = "tfss-3bed858a-35f9-4732-9bf6-92092bb85fbb-Filename4.zip";
                url = "http://files.parsetfss.com/f2b42f57-532e-4e84-b475-557854af5b6c/tfss-3bed858a-35f9-4732-9bf6-92092bb85fbb-Filename4.zip";
            };
            createdAt = "2015-10-06T18:10:15.356Z";
~~~

looks like I can just string replace the http to https...
But if parse files.parsetfss.com supports https should not just report as https

**Comment by nlutsenko** [comment]
The part with the REST API is tricky...

We have clients beyond iOS, including Android (with some very old versions) as well as IoT devices. Since the requirement for `https` is only enforced on iOS/OSX/watchOS/tvOS at this point - we did the change on the client SDK (which you can actually see in code), which got us the ability to transparently support `https` on files as well guaranteed the fact that no other platform is going to be impacted by this move.

Workaround in your case: If you encounter `files.parsetfss.com` domain - that domain fully supports `https` and you can simply rewrite the scheme on the client to use `https`. We might change this behavior in the future, but it's very unlikely.

**Comment by khoogheem** [comment]
Thanks.

I get the idea of not changing it to just https as it is more of a hangup the Apple side right now.

just add a secureUrl line ;)-

**Comment by nlutsenko** [comment]
:wink: Glad it helps.

**Comment by dlove9999** [comment]
btw....deleting all of the images in my Parse class and then adding them back resolved the issue.  So the problem was in that the old images where using old path.

**Comment by plaudev** [comment]
Hello, I have same issue using iOS SDK 1.14.2. My parse server is hosted on heroku. Is it better to open new ticket or reopen this one? Thanks

**Comment by fauxpaw** [comment]
I also am having this issue using SDK 1.14.2 and heroku with the parse-server-example deploy method.
