### ISSUE TITLE
CrashReporting with wrong build number

### ISSUE THREAD

**Issue by Silkjaer** [ParsePlatform/Parse-SDK-iOS-OSX#384]
From my experience: If an app has crashed and is first opened again after updating the app, the pending crash report will be sent with the build number of the updated app, and not the build number the crash actually happened in.

**Comment by nlutsenko** [comment]
Hey @Silkjaer, will look into it.
Looks like there is no workaround for this at this point, so sorry.

**Comment by nlutsenko** [comment]
Hey @Silkjaer, we've decided to deprecate Crash Reporting at Parse, so there are no updates going to be made to it. We sent out an email to active users of Parse Crash Reporting earlier today. Here is a copy of that email:

---

Update to Parse Crash Reporting

Hi there,

At Parse, we're always working to improve your developer experience. Last December, we launched Parse Crash Reporting with the goals of recognizing, tracking, and ultimately resolving crashes in your app.

In the time since, we've seen huge strides being made within the industry's native solutions. These native experiences have the advantage of being more tightly integrated into your build and release process, offering a more robust, streamlined, and frictionless development experience for you.

The Parse Crash Reporting tool is now being deprecated in favor of these great native solutions. We will continue supporting Parse Crash Reporting until March 1, 2016.

Here's how you can smoothly switch from Parse Crash Reporting to Apple or Google's offerings:

Apple Docs
Google Docs
We're constantly tackling new challenges to help you build better than ever before. Please reach out if you have any questions or concerns to community@parse.com.

The Parse Team
