### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by xissburg** [ParsePlatform/Parse-SDK-iOS-OSX#398]
I have no idea how and why this is happening but it's happening. Quite frequently now. It happens in different places, in different situations. I don't know an exact sequence of steps to reproduce. Here's a full backtrace: https://gist.github.com/xissburg/a65549d78abbe0a8572f

I am just accessing a PFObject property and the deadlock happens.

**Comment by nlutsenko** [comment]
Hey @xissburg, thanks for the report. Stack trace here is definetly helpful.
From symbol names in the stack trace - I can see that you are using a quite old version of the SDK.
Any chance you can update to the latest one and retest? (at the time of writing this is `1.9.0`).
We had few fixes around deadlocks in few recent releases.

**Comment by xissburg** [comment]
It looks like I will have to upgrade my project to Swift 2 and Xcode 7 first.

**Comment by nlutsenko** [comment]
I am almost sure everything is still going to work on Swift 1.2 and Xcode 6.4 with the current latest version, but let me know if it doesn't.

**Comment by xissburg** [comment]
I get the same problem described in this issue https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/298.

**Comment by kevflynn** [comment]
I'm getting lots of Deadlocking as well. Next time I replicate, I'll post a stacktrace.

**Comment by kevflynn** [comment]
Here's the stack trace - https://gist.github.com/kevflynn/3deb9da4628a48e49ec0

**Comment by richardjrossiii** [comment]
Thanks for the trace. Any chance you can post the output from all threads (`thread bt all`) in the lldb console.

**Comment by kevflynn** [comment]
Here you go @richardjrossiii https://gist.github.com/kevflynn/00d04bc8df93c1f9ba79

**Comment by rudywen** [comment]
I'm also seeing similar deadlock issues.  Here is the BT: https://gist.github.com/rudywen/31ec2f54574be20784ab

This issue is blocking our app release.  Is there anything we can do to help debug the issue?

**Comment by richardjrossiii** [comment]
@rudywen That deadlock is actually not directly Parse's fault. What's happening here is that every thread in the default thread pool (usually there's 16 threads in the thread pool for iOS/OSX) is waiting on a task to be run in the same thread pool (in this case, it's attempting to create the PFFIle cache directory if necessary), but because all thread pools are going attempting to wait on the same thing at the same time, there's no dispatch queue available from the system to attempt to create the directory.

You should probably rethink your architecture if you're trying to concurrently download so many parse files, or use your own network/caching stack using `file.url`, as the architecture in Parse is not designed for so many concurrent downloads.

**Comment by nlutsenko** [comment]
@richardjrossiii is right on this one, it's purely too many files being downloaded at the same time.
We can optimize for it, but in all sanity - please simply add the file downloads to an operation queue, as downloading ~30 files concurrently is probably not what you want.

**Comment by rudywen** [comment]
@richardjrossiii @nlutsenko Thanks for the suggestions. We'll correct it on our end.

**Comment by xissburg** [comment]
After upgrading to Parse 1.9.0 I haven't experienced this issue again. Thanks for the great job guys!

**Comment by nlutsenko** [comment]
Glad it helped!
