### ISSUE TITLE
countObjectsInBackgroundWithBlock starts returning count 1

### ISSUE THREAD

**Issue by santanu4ver** [ParsePlatform/Parse-SDK-iOS-OSX#40]
Last known working date: 16th August 2015
Affected app: VoteYourSpider
Using Parse (1.7.5.3)
Using ParseUI (1.1.4)

```
query.limit = 1000
query.whereKeyExists("name")
query.countObjectsInBackgroundWithBlock { (count, error) -> Void in
            
        if error == nil
        {
              self.maxRecordsCount = Int(count) - 1
        }
}
```

The above code suddenly starts returning count:1.

**Comment by nlutsenko** [comment]
Hey @santanu4ver, thanks for reporting. I'll take a look shortly.

**Comment by santanu4ver** [comment]
Hey @nlutsenko any good news on this, lately?

**Comment by santanu4ver** [comment]
Some more input for yours investigation. I recently noticed while testing through multiple projects that whenever I query this following before aforesaid query, things breaks down; which is very odd!

```query.getObjectInBackgroundWithId("46")
{
      (value: PFObject?, error: NSError?) -> Void in
      if error == nil && value != nil
      {
             println(value) // this does prints positive result
      }
      else
      {
             println(error)
      }
}```

This is quite odd. If I remove this call, then Parse starts working usually! In need, *getObjectInBackgroundWithId* is my app's first query, and then *countObjectsInBackgroundWithBlock*.

Please, response something. My whole Parse dependent app terribly broken now!

**Comment by nlutsenko** [comment]
Aha... @santanu4ver, thanks for adding this.
Are you reusing the query that you are performing against Parse?

`getObjectInBackgroundWithId` will set the limit to 1, so any find that you perform on the same query will always return 1 object. (this is noted in the documentation for `getObjectInBackgroundWithId:`
In addition to that - it will add the condition for `objectId == ...` to the query (this one is probably wrong, since there is no way to remove that condition further, and I'll fix it).

Could you try recreating your queries from scratch instead of reusing them and let me know how it goes?

**Comment by santanu4ver** [comment]
Yay! That solved the matter! Even the issue raised in https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/41 also resolved by using different instances of queries! Sorry, I overlooked the fine details in API doc ;) Thanks @nlutsenko!
