### ISSUE TITLE
Phones 6 and 6+ restored from iCloud back up not registering

### ISSUE THREAD

**Issue by ernestome** [ParsePlatform/Parse-SDK-iOS-OSX#404]
Hello,
  We have a user that recently upgraded to an iPhone 6+, they had two apps that we use the Parse SDK to deliver push alerts to. When the owner upgraded to a new iphone 6+ and restored their apps via iCloud they ceased to receive push alerts, the apps in question are News 9 and News on 6, upon resetting the News9 app the user began to receive pusher alerts, the News on 6 app has not been resetting and we are refraining from resetting to see if we can come up with a solution that does not require work on the side of the end user which may not know to do this.

The device token ID for that app is 2b60b6571cb8e64b9c65ca4da3c0e2ca7ebb330e1ea67c25f10f556e77622f15 which does not appear in the device token ID database.

**Comment by nlutsenko** [comment]
Hmm... this sounds super strange, since we explicitly mark our files as not restorable from backup.
The few things that might help us diagnose the issue better:
- `PFInstallation.currentInstallation()` on both devices should probably match in `objectId` or at least in `installationId`
- If you try to update the deviceToken on the newly restored device - can you save `PFInstallation.currentInstallation()` or it gives you an error?

I wish I could help you more with the information that you provided, but it appears to be some data consistency issue on the client, and getting as much information as possible would be just amazing.
(if you could attach a snapshot of both apps data, that would be tremendous help)

**Comment by ernestome** [comment]
Hello,
  We were able to reproduce this on another device however this time the new device ID did register and was found in the parse database, however it did not receive push alerts. Additionally the expectation is when starting app after first time after restoring is that you are prompted to accept push alerts which did not happen, regardless after turning them on they did not appear. Attaching charles log file to this drop box link from when the device was restored and app started up.

https://www.dropbox.com/s/bmx6g3w9krfegom/Parse_payload_for_iOS9_iPhone6S.chls?dl=0

**Comment by ernestome** [comment]
The old and new device tokens are below for their respective apps.

Old Device Token
News On 6
1bb80e53e0eeddac7ae4f24d23773cea8a47d4c127b6f0f56d6e6ed04bd8b877

News 9
d89cccc2ab05ec8bca136b873c649f9b89702c813be2f115a56f510ef686802a


NEW device tokens

News On 6
5a0d9c8d8bf6c46344aa98dc4c5312b55fef3e61ea07c7a77f00ba03d0643258

News 9
b070521ae6063c0da4ccff9bd12f629d07bf52769c8a95e6cf8ee6925e58ce68

The first device type was an iphone 6 running ios 8.4 the apps were restored to a new iphone 6s.

**Comment by ernestome** [comment]
The apps are currently on version 1.4.2 of the Parse SDK.

**Comment by nlutsenko** [comment]
@ernestome, before I go dive deep into this... 
There is one piece - could you try using the latest SDK (1.9.0 at this moment)?

1.4.2 was released 364 days ago (I can't say a year, since it was Oct 15 :grin:), which at this point has so much internal changes, that the issue could be already resolved (most likely), as well as finding a workaround would be more time consuming than upgrading to the latest version.

Also, we are doing our best to minimize amount of API changes (specifically removals, and deprecations), so the upgrade experience should be as painless as possible.

**Comment by ernestome** [comment]
Hello,
  Appreciate the response our team is in the process of updating the our app to the latest SDK however it does not appear this issue was ever directly addressed based on release notes. So we are concerned that when we create the newest version of the app the issue will still be present.
