### ISSUE TITLE
BugsPFAnalytics is not working correct when tracking push notification

### ISSUE THREAD

**Issue by robertvvv** [ParsePlatform/Parse-SDK-iOS-OSX#411]
When I send a notification via web console. And I can receive the push notification on my iOS device, and I can open view controller correctly.

But when I open my web console I found the track is not working. As below.
![qq20151014-1](https://cloud.githubusercontent.com/assets/3982338/10473417/cb82aaaa-725d-11e5-8147-7eec70e6eba0.png)

But In my  “Push Open” event on Analytics Page, The number of opens is correct.

What can I do next?

**Comment by nlutsenko** [comment]
Hey @robertvvv, thank you for the report!
This sounds like purely a website/backend bug, since you are seeing inconsistent data in the dashboard (No push opens in Push Console, but numbers are visible on the analytics page).

You could file one at https://parse.com/help , since we are still using FB Bug Tool to track those,
