### ISSUE TITLE
Not compiling when used with Extensions.

### ISSUE THREAD

**Issue by chayelheinsen** [ParsePlatform/Parse-SDK-iOS-OSX#43]
I keep getting sharedApplication is unavailable on iOS (App Extension).
This has happened in PFPush, PFApplication, PFPushUtilities, PFLocationManager and PFNetworkActivityIndicatorManager. I am also getting ld: warning: linking against dylib not safe for use in application extensions:

**Comment by nlutsenko** [comment]
Hey @chayelheinsen, thanks for reporting this.
Feel free to use precompiled packages (from releases page or built from source by instructions in the README) if you are linking with app extensions for now, but we are going to fix this in few upcoming releases, so you can compile from source.

The warning that you see is probably because you are using Cocoapods with `use_frameworks!` enabled, which produces a dynamic framework instead of static one. Try removing `use_frameworks!` from your Podfile or again using a precompiled static framework.

**Comment by codywinton** [comment]
@nlutsenko - Removing `use_frameworks!` doesn't resolve the issue. For example, I ran into an error with `PFAlertView` saying that `UIAlertView` is not available. Also, line 53 `UIWindow *keyWindow = [UIApplication sharedApplication].keyWindow;` gives the same error mentioned above.

**Comment by nlutsenko** [comment]
`use_frameworks!` - related to the warning that you were getting aka `linking against dylib not safe...`
The workaround for extensions right now is to use a precompiled package, until we get there.

**Comment by chayelheinsen** [comment]
@nlutsenko I removed Parse from my pods and now I can get an archive, but their generic. I'm not sure if this is from Parse or just my settings being wrong. It's most likely my build settings being wrong.

**Comment by nlutsenko** [comment]
Not sure I follow, you can go to and get the releases package - it includes Parse.framework and Bolts.framework
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases

If you are interested in things like Crash Reporting or ParseTwitterUtils - you can get the full download from https://parse.com/docs/downloads
