### ISSUE TITLE
PFUser subclass really slow to save 

### ISSUE THREAD

**Issue by elondon** [ParsePlatform/Parse-SDK-iOS-OSX#432]
I'm experiencing incredibly slow saving for my user object with a nested array and I'm not sure why. My object model is not complicated and I don't have much in the database yet. 

    Post* post = [Post object];
    post.title = "My Favorite Post";
    
    [currentUser addObject:post forKey:@"posts"];
    [currentUser saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error)
    {
        NSLog(@"Saved!");
        block(succeeded, error);
    }];

The callback block does get called and the post is saved and added to the posts collection of the current user with no error - however, it takes a really long time. Has to be a couple of minutes. I've tried saving the post first, and it saves in a 3-5 seconds which is slow but acceptable, but I still get the same several minute wait when I add it to the current users Posts and save the user. Aside from a couple of arrays, both of these models are just strings and dates. My user is a subclass of the parse User class.

Any idea what causes this type of behavior and whether or not there are limitations I should be aware of that would cause something like this to happen? Is there anything I can do to improve the time it takes to save objects?

Thanks!

**Comment by nlutsenko** [comment]
Hey @elondon, thanks for the report.
Shouldn't happen in the wild, it should save almost instantly...

Any chance you are seeing this on a specific iOS/OSX version or with a specific SDK version?
One thing that might help us diagnose the problem and distinguish it between client and server are network notifications that we have for debugging. You can read more about them [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool).
If you could post the log for all the network connections logged since app start time - that would be super helpful to diagnose where the issue is coming from, as well as follow up further.
