### ISSUE TITLE
Cannot compile Parse 1.9.0. 'Bolts/BFDefines.h' file not found

### ISSUE THREAD

**Issue by Ricardo1980** [ParsePlatform/Parse-SDK-iOS-OSX#452]
Using xcode 7.0.1 7A1001 and 
pod 'Parse', '1.9.0'
pod 'ParseFacebookUtilsV4', '1.9.0'
pod 'ParseUI', '1.1.6'

It seems also happens if I use 1.8.5

/Users/personal/Desktop/sharewifi-ios/Pods/Bolts/Bolts/Common/BFTaskCompletionSource.h:13:9: 'Bolts/BFDefines.h' file not found

Impossible to compile my project again.
Any help?

It seems 1.3 and 1.1 of Bolts are being mixed.

**Comment by nlutsenko** [comment]
Hey @Ricardo1980, thanks for the report.
I am not sure how `1.1` and `1.3 ` are mixed in your case?
Can you double check that you don't have another copy of Bolts.framework in your checkout or basically anywhere where `FRAMEWORK_SEARCH_PATHS` build setting can find it?
(maybe in `~/Documents/FacebookSDK` - since that was the path where FB SDK installed for a long time)

**Comment by Ricardo1980** [comment]
My mistake. I deleted everything regarding cocoapods, launching pod install and works fine.
Thanks a lot for help.
