### ISSUE TITLE
A server with the specified hostname could not be found

### ISSUE THREAD

**Issue by JRam13** [ParsePlatform/Parse-SDK-iOS-OSX#482]
This is a sporadic issue (and an old one at that). The problem seems to happen more often when switching between networks. It can happen when on wifi, but this occurs more often on mobile networks. 

There have been multiple stackoverflow questions on this, no real solutions. The only known solution to this is restarting the phone. Otherwise, you can never get parse to connect again on that network. 

http://stackoverflow.com/questions/27697774/parse-com-nsurlerrordomain-code-1003-in-cellular-not-in-wifi

Please note that this is not a network connection issue!

<img width="639" alt="screen shot 2015-10-27 at 3 34 49 pm" src="https://cloud.githubusercontent.com/assets/3259292/10771717/50ed4d8c-7cc0-11e5-8205-3a12d18bac67.png">

```
2015-10-27 15:32:32.330 Daybook[5707:2009777] [Error]: Network connection failed. Making attempt 4 after sleeping for 15.106310 seconds.
2015-10-27 15:32:48.741 Daybook[5707:2009992] [Error]: A server with the specified hostname could not be found. (Code: 100, Version: 1.9.0)
```

**Comment by JRam13** [comment]
Update: I have noticed this issue happening since 1.8.x. I have the latest version of the Parse SDK (1.9.1) and this is still a problem.

**Comment by nlutsenko** [comment]
There is not much that changed between these versions in terms of networking between 1.8.x and 1.9.1,
the error description here says that it might be a DNS issue, which is outside of our control, since we rely on NSURL (Foundation/CFNetwork) via NSURLSession to do the networking for us, and if this doesn't work this way, it would mean that this will fail for any general use case against `api.parse.com`.

I would suggest filing an issue on https://parse.com/help, since we are still using FB Bug Tool to track server-side issues.
