### ISSUE TITLE
Remote Notifications Request not called

### ISSUE THREAD

**Issue by zqazi114** [ParsePlatform/Parse-SDK-iOS-OSX#525]
Hello. I am developing an application which uses Parse for user database services and to implement a messaging protocol. The application is built on iOS.

I have come across an odd problem. One of my developer devices no longer prompts the user to 'Receive Remote Notifications'. I have the application set up such that every time a user logs in or signs up, I check whether they have granted remote notifications and if not I make the request. I need to do this to have a valid PFInstallation to target notifications. 

The device seems to be caching the Remote Notification state for my app, meaning that even if I uninstall and reinstall the app, it automatically marks it for remote notifications and hence I cannot retrieve the device token to save to my PFInstallation. I have tried to leave the application uninstalled for 24 hours as per a StackOverflow suggestion to no avail.

Why is my device storing the user's response to 'Allow remote notifications' even after re-install? Nothing I do clears this setting. Is there another way for me to fetch the device token upon app startup so I can register my Installation class?

Thank you.

**Comment by nlutsenko** [comment]
Hey @zqazi114, `UIApplication.registerForRemoteNotifications()` call should register for remote notifications and you'll get a callback in your app delegate regardless of whether the user agreed to receive notifications previously or not (regardless of the setting caching).

Push notifications registration on iOS happens in system frameworks, since the delivery is handled by the system, so caching of this setting is something outside of our control. If you explicitly need to test the first time the user agrees to receive notifications - I would suggest making a full reset of the device.
