### ISSUE TITLE
Symbol not found: _OBJC_CLASS_$_PFACL

### ISSUE THREAD

**Issue by ankurarora** [ParsePlatform/Parse-SDK-iOS-OSX#526]
I was using Parse with iOS 8.4 and Xcode 6.4 successfully. The parse version which I was using 1.7.5. Recently, I have updated my pods to latest and parse version is now 1.9.1 and also project settings to compile for 9.1. Secondly, I am using Xcode 7 now.

Everything compiles good and build is successful. However, when I am trying to run the application I get below error.

dyld: Symbol not found: _OBJC_CLASS_$_PFACL Referenced from: /Users/ankur/Library/Developer/CoreSimulator/Devices/5924BE2D-5302-4140-B9C1-4E1D671B3C1F/data/Containers/Bundle/Application/9C046EDE-986D-4A6E-B461-38D7F859F5C7/myapp.app/myapp Expected in: flat namespace in /Users/ankur/Library/Developer/CoreSimulator/Devices/5924BE2D-5302-4140-B9C1-4E1D671B3C1F/data/Containers/Bundle/Application/9C046EDE-986D-4A6E-B461-38D7F859F5C7/myapp.app/myapp

I looked for PFACL and it is part of PODS. I can find it under PODS.

Not sure what is wrong here but looks like something missing?

Thanks for the help - Ankur

**Comment by nlutsenko** [comment]
Hey @ankurarora, looks like you are integrating Parse SDK as a dynamic framework via CocoaPods.
Could you double check if the framework generated by CocoaPods did properly integrate with your end application? The first version that was opensource is 1.8.0, meaning that know everything compiles from source when you build your application (Parse SDK including), and it might have affected the installation of CocoaPods if you did not fully integrate it.

Let me know how it goes. If you can provide a consistent repro project that has this problem - I could jump right in and fix it, but otherwise - the only thing that comes to my mind is to double check proper integration of CocoaPods in your project.

**Comment by ankurarora** [comment]
Hey @nlutsenko , Thanks for the response. I investigated little more on this and found that earlier version was able to run without [Parse enableLocalDatastore] however with newer version the moment I put that extra line of code the app is running perfectly. Though there are not errors while compiling the app in both cases. If it is mandatory to enable local datastore then I think having a meaningful error message would help to understand the reason of error better.

Thanks for helping, the problem is sorted

Ankur

**Comment by ankurarora** [comment]
Hey @nlutsenko , I investigated further and found that earlier version was able to run without [Parse enableLocalDatastore] however with newer version the moment I put that extra line of code the app is running perfectly. Though there are no errors while compiling the app in both cases.

I think it should be handled greacefully if enabling local datastore is mandatory. 

Thanks for helping, the problem is sorted

Ankur

**Comment by nlutsenko** [comment]
Sounds super strange and definitely not something we intetfully enforced. 
Any chance you can add a retro project to this?

**Comment by ankurarora** [comment]
Yes I can try to do a retro project but give me some time plz
