### ISSUE TITLE
parse iOS  1.9.0 IncludeKey not working

### ISSUE THREAD

**Issue by lifeisfunny** [ParsePlatform/Parse-SDK-iOS-OSX#533]
includeKey stopped working on parse since i update from 1.8.5 to 1.9.1  ,  I tried 1.9.0  as well but there are not return object from include key

**Comment by lifeisfunny** [comment]
just double check my log and yet appear that include key are not getting any data back  from the key which in my case are pointer to user

**Comment by richardjrossiii** [comment]
For the record - `-includeKey:` does not work with queries from local data store. So if you're making a query with `-includeKey:` to LocalDataStore, it will always return no objects (Note to self: fix that).

If you're having an issue when fetching from the server, please file a bug instead with the backend team over at http://parse.com/help.

Otherwise, you're going to have to be much more specific (e.g. code examples) in order for us to be able to help you.

**Comment by lifeisfunny** [comment]
its querytable view controller.    On the query for table , when I adding include key on the pointer value which at this point is a user pointer ,  but the return object has nothing related to user object.

**Comment by lifeisfunny** [comment]
Ya. It is a backend issue I think.   Thank for pointing the way , instead sharing the issue with your team.

**Comment by richardjrossiii** [comment]
Sounds good. Feel free to re-open this issue if the problem turns out to be SDK-based.
