### ISSUE TITLE
Empty Cellular data package blocking push notifications after wifi reconnect  

### ISSUE THREAD

**Issue by raimondo** [ParsePlatform/Parse-SDK-iOS-OSX#557]
When cellular data takes over from wifi when their's no wifi connection available
If their is no money in a users cellular data package , when wifi reconnects push notifications fail to reach device until devices is put on flight mode and off again
Ive tested this on two different service providers and this issue occurs on both providers

**Comment by nlutsenko** [comment]
Since push notification on the client-side are delivered and handled by the system, I would say this is an Apple bug. If you compare iOS to Android - all of the interactions, including receiving, displaying and alerting the user of a notification, unless the application is open is handled purely by the operation system on iOS.
I would suggest filing a bug against Apple aka radar [here](https://bugreport.apple.com).
Feel free to comment here with a link to it (or just a number) and I'll gladly duplicate it, so it's more visible on their end.

**Comment by raimondo** [comment]
Hi Nikita 

I agree with your suggestion 

I will file a bug report with Apple and keep you in the loop

Thank you for your feedback

- Ray
