### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by weiwarren** [ParsePlatform/Parse-SDK-iOS-OSX#559]
I'm trying to build the project following the build instructions, received following error with an empty build folder:

<pre>
** BUILD FAILED **

The following build commands failed:
	ExternalBuildToolExecution Bolts-iOS
(1 failure)
Failed to build framework for iphoneos.

</pre>

Tried with Xcode 6.

**Comment by nlutsenko** [comment]
Hey @weiwarren, thanks for the report, few questions:
- Did you checkout all the submodules for the repo aka `git submodules update --init --recursive`?
- Can you please post the full build log here, as I hope there is more information there
- Could you retry this with Xcode 7 (it's been 2 months since it's release)?

We are building every commit via Travis, so I am not sure about the reasons it happens here for you, but am confident we'll get to the source of it.
