### ISSUE TITLE
Background return queue parameter

### ISSUE THREAD

**Issue by lkraider** [ParsePlatform/Parse-SDK-iOS-OSX#576]
As it is now all `inBackgroundWithBlock` calls that accept a block will execute that return block on the main thread.

This can cause performance problems where we need to chain many calls through Parse and other frameworks before presenting the data in the UI, or otherwise just process data in the background.

Please offer an interface with an additional parameter `inBackgroundWithBlock: targetQueue:` that allows us to define the queue executor for the return block.

**Comment by nlutsenko** [comment]
Turns out you can actually do this right now, via Bolts Tasks (you can read more about the Bolts.framework [here](https://github.com/BoltsFramework/Bolts-iOS).

Let me give you an example with `PFUser.become`:
```objc
BFExecutor *executor = [BFExecutor executorWithDispatchQueue:dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)];
[[PFUser becomeInBackground:@"yolo"] continueWithExecutor:executor withBlock:^id(BFTask<PFUser *> * _Nonnull task) {
    // task.error is going to be non-nil if it has an error
    // task.result is going to have PFUser if the operation succeeded
    return nil;
}];
```

You can also create executors with blocks or NSOperationQueue...
Hope this is what you are looking for.

**Comment by lkraider** [comment]
Great, thanks.
