### ISSUE TITLE
PFInstallation not changing updatedAt date when saving the current installation in background with no new data

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/Parse-SDK-iOS-OSX#597]
Summary of the bug:
There is an issue when calling [[PFInstallation currentInstallation] updateInBackground] in the iOS SDK. It used to be that whenever you called that method, the updatedAt timestamp on the installation object in the data browser would update, but now it only does if the installation has changed. I use custom analytic software based on the updatedAt date, and now it only detects a change when something has changed. Please fix this bug, as it used to work fine.

Steps to reproduce the bug:

1. Create an installation using the iOS SDK
2. Update that installation without changing any data and observe the updatedAt date does NOT change.
3. Please fix :)

Relevant code snippets from your implementation:
~~~
NSLog(@"Your code goes here");
~~~

SDK version: 1.9.1

**Comment by nlutsenko** [comment]
Hey @dcdspace, thanks for the report.
This is very much intentional, and if it was working differently before - that was a bug.
It will not update an `updatedAt` date if there was no change to the data.

All the data here is coming from the server (in the case of `updateInBackground`) - meaning it actually does perform a fetch from the server, including the latest updatedAt date, but if there was no change to the data on the server - it will come back the same without any change.

If you put a little more information on why updatedAt matters in your use case - I might try to help you come up with a different way of doing the same thing.

**Comment by dcdspace** [comment]
Thanks for the help @nlutsenko. I have a web backend in which I call the REST API and query it for installations, sorted by updatedAt to see what installations were active most recently. Due to this change, only installations with changed data are being returned at the top. I guess I could try adding a custom column called "lastActive" updated with the date when the installation was last active. Any suggestions?

**Comment by nlutsenko** [comment]
`lastActive` is a good idea, it should work great.
`updatedAt` would have a side effect anyhow when say people would update the app (it triggers the installation update with new appVersion/etc), so using a custom column on Installation would be higher signal.
