### ISSUE TITLE
Unwanted cache result with "findObjectsInBackgroundWithBlock"

### ISSUE THREAD

**Issue by Helmikku** [ParsePlatform/Parse-SDK-iOS-OSX#598]
Hi,

I'm currently facing an issue with parse iOS SDK v1.10.0. "findObjectsInBackgroundWithBlock" would give me the last local modifications of a PFObject instead of the last cloud database modification. After several tests, here is an example with my observations.

I initially load (with "findObjectsInBackgroundWithBlock") one "Challenge" PFObject during the app launch. Its "status" attribute is "pending".

The user can accept this challenge in the app. To do so, I locally change the "status" attribute of the PFObject to "accepted". Then, for security purposes, I call a cloud function to save the new challenge's status. The cloud database version of my PFObject is also "accepted".

Later, I want to push an update of that same PFObject. I change the cloud database status to "starting".

I send a push to the app, so the app calls "findObjectsInBackgroundWithBlock" to find the challenges with "starting" status. It does find the right PFObject, but with its old local data: its status is still "accepted". The query works fine, only the data isn't up to date.

Is it a normal behavior? Does the locally changed data always prevail over cloud data?

By the way, I've enabled localstore but I do not pin this PFObject.

Thanks for the feedback!

**Comment by nlutsenko** [comment]
Hey @Helmikku, yes, with Local Datastore, since every PFObject is guaranteed to be a single instance in memory - both the client and server changes are squashed together, or rather the client changes are always applied on top of the server changes, even when you perform fetch on the object or if you get the same object from cloud function result.

You can revert the changes (reset them back to server state) by calling `challenge.revert()` or `challenge.revertObjectForKey()`, which will remove any client change and reset the state of the key or full object back to the last known server state.

Let me know if this helps, or if there is anything else I can help you with.

**Comment by Helmikku** [comment]
Hi @nlutsenko, thanks a lot for your answer. :+1: 
I thought that only pinned objects were concerned by single instance :) Revert is a function I didn't know either, very helpful for "cancel" purpose.

Have a nice day!

**Comment by jenlai1345** [comment]
Thank you very much nlutsenko!
You saved the day!
