### ISSUE TITLE
No such module 'Parse'

### ISSUE THREAD

**Issue by telip007** [ParsePlatform/Parse-SDK-iOS-OSX#60]
If I try to use Parse with iOS 9 beta i get the issue "No such module 'Parse'". <p>I use the newest Xcode 7 beta and Swift.</p>

**Comment by telip007** [comment]
I checked everything twice and the Parse framework is also included in my Project.

**Comment by nlutsenko** [comment]
Hey @telip007, can you include a repro project or provide some details about your specific configuration?
Also - I encourage to checkout [StarterProjects](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.8.) that we have on releases, they are actually using a pre-built Parse.framework.

**Comment by telip007** [comment]
I opened a Repro with the same config as my App without any Content only the frameworks. But I still get this error every time I try to build this "App". 
The Repro ->
https://github.com/telip007/testApp

**Comment by telip007** [comment]
Sorry my Internet is slow af. Now the complete project with the frameworks is online.

**Comment by telip007** [comment]
First I get a "Build succeeded" but when I try to use Parse,  I get the error or sometimes I get a "Build succeeded" and the error at the same time.

**Comment by telip007** [comment]
@nlutsenko

**Comment by nlutsenko** [comment]
Looking in depth right now, will update here.

**Comment by nlutsenko** [comment]
@telip007 after inspecting the project locally, I can't find anything obviously wrong with it.
If you add code to actually use Parse - it will continue to work, as well as if you try to use Xcode 6.4 - it will also continue to work.

I went further and recreated an empty project from scratch just to test this behavior - it works like a charm with a new empty project and Parse+Bolts, so I suspect there is something wrong about your project.
Please try recreating the project from scratch using Xcode 7 and let me know if it helps.

Since the code could be built - and not only Parse and Bolts couldn't be imported, but rather any third party framework I suspect this is something related to Xcode 7 swift compiler/preprocessor behaving in a weird way.

**Comment by telip007** [comment]
Hmm ok, I will try.

**Comment by telip007** [comment]
*it

**Comment by telip007** [comment]
I have one question left 😏 Should I use tbd instead of the dylibs or are the dylibs required ?

**Comment by telip007** [comment]
@nlutsenko

**Comment by nlutsenko** [comment]
.tbd is iOS 9/OS X 10.11 new thing for dynamic libraries that are built in, so it's absolutely fine to use them instead of .dylibs

**Comment by grantkemp** [comment]
Any idea when this will be fixed?

**Comment by nlutsenko** [comment]
@grantkemp, this issue is closed and is considered fixed.
If you are still experiencing any problems - I would suggest opening a new issue.
