### ISSUE TITLE
App not renderign on iOS

### ISSUE THREAD

**Issue by olilogic** [ParsePlatform/Parse-SDK-iOS-OSX#608]
Hi my app http://www.malibuhotchoc.co.uk/ is rendering fine on my desktop but not on iOS does anyone know any reason for this? thanks Oli

**Comment by nlutsenko** [comment]
Hey @olilogic, are you using an iOS SDK for the app? Or it doesn't render when you are trying to access the website in iOS Safari? If it's the latter - I would suggest filing an issue on our JS SDK at https://github.com/ParsePlatform/Parse-SDK-JS
(feel free to reopen if the issue is indeed about iOS SDK)
