### ISSUE TITLE
PFInstallation badge number is always 0

### ISSUE THREAD

**Issue by janmisar** [ParsePlatform/Parse-SDK-iOS-OSX#630]
I'm trying to decrease badge badge number according to this blogpost (http://blog.parse.com/announcements/badge-management-for-ios/), but when I compare current badge number to non-zero, it always fail because installation's badge number is always 0. So badge number is never decreased in DB. PFInstallation just does not return right values from Parse DB.

![screenshot-db](https://cloud.githubusercontent.com/assets/3321064/11652233/e60a1566-9d96-11e5-82f8-39046ec11a6f.png)
![screenshot-local](https://cloud.githubusercontent.com/assets/3321064/11652328/665f01ea-9d97-11e5-9a41-33f6a61ccbc6.png)

I can remove lines with condition and decrease badge every time of course but I don't think it's right solution. Why PFInstallation is not updating even if I restart app?

**Comment by nlutsenko** [comment]
Hey @janmisar, in order to get the latest `badge` from Parse - you would need to explicitly `fetch`/`fetchInBackground` `currentInstallation` object. Since `currentInstallation` is a synchronous call - we wouldn't want to block the current thread on network fetch, as well as having an explicit call to fetch `currentInstallation` lets you optimize the usage of network for your application/use-case.

Let me know if you indeed fetch the installation and it's still missing badge.
I kind of made an assumption here that you didn't, based on the screenshot/details that you posted.

**Comment by janmisar** [comment]
Hey @nlutsenko, thanks for response, you're right. I had no idea I have to explicitly fetch installation object, so it's clear now.
Anyway I don't seem good to publish not working snippets of code on official blog, it's a little confusing.

**Comment by petritzdesigns** [comment]
For some reason it is not working for me. I used the fetchInBackgroundWithBlock function and when i debugPrint it out it says badge=10, but when I want to retrieve the badge value it always returns 0.
