### ISSUE TITLE
Queries on public classes fail while user has invalid session

### ISSUE THREAD

**Issue by hipwelljo** [ParsePlatform/Parse-SDK-iOS-OSX#671]
I have discovered that once a user's session is invalidated, all future requests will fail until the session is valid again, including queries for data that is available to query publicly without logging in.

This is biting me because my Sign Up screen requires the user select from some PFObjects that are queried from a publicly accessible class. I show a list of options, they tap on one, then I set that object on the new user object created when they tap Sign Up. The problem arises when their session is invalidated. I present the log in or sign up screen, but if they want to sign up they cannot, because the query for the information required in sign up fails with error `Error Domain=Parse Code=209 "invalid session token"` (despite the fact the user doesn't need to have an active session to access the data).

Therefore it is impossible for the user to create a new account after they logged into an account and said account had its session invalidated. This will occur in a few situations: the account session actually expires, the user logged in with Facebook and its session expired, or the user was deleted altogether (perhaps because they posted something inappropriate). In all cases I get the 209 invalid session error, and I need to support the ability to sign up at that time - especially the latter because it's impossible for them to sign into their account that was deleted.

I attempted to log the user out once I find out their session is invalidated, but even this request fails with the same invalid session error.

Shouldn't queries simply succeed when it doesn't require they be logged in anyways? Should we be able to force log out of an account that has an expired session?

**Comment by nlutsenko** [comment]
Hey @hipwelljo, the issue that you are getting is somewhat 'by design'.

Since you are trying to query/get the data and are sending the user's session token - the first check that is being done on the server is whether that session token is valid or not. We could silently swallow this error if you are trying to access/query objects that are public read or write, but that would still be not as useful, because your app wouldn't know if the session token is not valid anymore.

I would recommend checking for `invalid session token` error, which on the client is represented as [kPFErrorInvalidSessionToken](http://parse.com/docs/ios/api/Enums/PFErrorCode.html#/c:@E@PFErrorCode@kPFErrorInvalidSessionToken), and if that is the case - simply call [PFUser.+logOutInBackground](http://parse.com/docs/ios/api/Classes/PFUser.html#/c:objc(cs)PFUser(cm)logOutInBackground).
That call will try to revoke the session token, and if it fails - you can ignore the invalid session token on it, since you already know that the session token is revoked.
After you logout your user - all calls to Parse won't include the session token anymore and you will be able to query/fetch the public data.

There is a good write up about revokable session handling logic in our [iOS Guide](https://parse.com/docs/ios/guide#sessions-handling-invalid-session-token-error), that you might find useful as well.

I hope this makes sense. Let me know if there is anything I missed or this solution doesn't quite fit your needs.

**Comment by hipwelljo** [comment]
This works for me even if confusing and odd. Thanks
