### ISSUE TITLE
Reset Password Through Email

### ISSUE THREAD

**Issue by jinnkafka** [ParsePlatform/Parse-SDK-iOS-OSX#69]
When implementing our own sign up for a user using Parse, we can set certain restrictions on password requirement (i.e. More than 5 characters, at least one number)
However, when an user reset his or her password through email, there is no restriction for their new password. They are able to set a new password as simple as "1" 
Is there a way we can set restriction for email password reset ?

**Comment by stanleyw** [comment]
Great suggestion.  No way to restrict it right now.  This is more a backend/website feature request, rather than an SDK issue.  However, I'm curious about your thoughts on this proposal: what if we offered an option on your Parse.com dashboard's app settings page that allowed you to specify some validation requirements for the password?  If the requirement is not met, then normal User object saving and the password reset would both fail.

You mentioned 2 types of constraints (character classes, length).  Are there any other common constraints?  How would developers want to define such requirements on a web UI?

**Comment by jinnkafka** [comment]
Thank you for the reply Stanley !
More email reset options on Parse.com dashboard would definitely work. I think if we look at Password requirement for most of the login system, it most likely narrows down to 
1.Contain at least one capital letter 
2.Contain at least one number
3.Password length more than certain characters 
I think if Parse.com put some radio buttons on email reset dashboard for developers to choose would be great.

**Comment by acegreen** [comment]
Just wanted to add a suggestion to this thread. I'm not sure if this already exists but it would be critical to have email confirmation for when a user signs up using Parse.

**Comment by hramos** [comment]
@acegreen if you're referring to email verification, that feature already exists. This can be enabled in your app settings in the parse.com dashboard.
