### ISSUE TITLE
Enable query cache and object pinning

### ISSUE THREAD

**Issue by moflo** [ParsePlatform/Parse-SDK-iOS-OSX#7]
Hi, I'm sure this is not easy but... we were surprised to see this caveat:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/61f68e9333206f0eebf15d5adab076a0ae7c4b71/Parse/PFQuery.h#L798

Could you please explain why it's not possible to enable a cache policy on a query while pinning is enabled -- even, seemingly, if the query cache policy is set on an object which will never be pinned?

Our solution was to disable pinning (by using a proprietary data store) and then enjoying the benefits of a liberal cache policy.

Thanks!

**Comment by nlutsenko** [comment]
Hi,

The biggest reason behind not having query caching with pinning is consistency and single instance management. Query cache can return different results (you can see it in code), based on the date your query ran. And since with Local Datastore enabled - you always have a single in-memory instance of any `PFObject` - having inconsistent data in cache is not helping with it.

We were exploring some ideas around being able to cache a query in LDS with auto-expiring pins.
cc @grantland to expand on this if I missed anything.

**Comment by grantland** [comment]
The biggest thing with query caching is that different states of the same object can be stored and that's ok since `ParseObject`s can have multiple instances without LDS. This doesn't play well with LDS's method of guaranteeing single instance, since pulling an object out of cache would interfere with the instance in memory and it's persisted state on disk.

**Comment by moflo** [comment]
Thanks for the clarification, @grantland. I'm sure this is a challenge, but wouldn't one solution be to provide some sort of granularity on LDS? In our application, we only ever want to pin certain PFObject classes. Is that possible? Thanks!

**Comment by grantland** [comment]
Unfortunately not really with our current architecture D:

**Comment by moflo** [comment]
Yup, understood. Perhaps I can have you close this issue and open (or convert this to) an enhancement request instead? Thanks!

**Comment by nlutsenko** [comment]
Sure, feel free to open an enhancement request we'll track that one.
