### ISSUE TITLE
Changes to array of pointers

### ISSUE THREAD

**Issue by artooras** [ParsePlatform/Parse-SDK-iOS-OSX#701]
Hi. Have there been changes to how arrays of pointers are handled? In the new Parse UI I can see that the contents of the array of pointers is now different from what it used to be. Previously it was just 3 fields - type (pointer), class, objectId. Now the array contains objects with all keys and values. This wouldn't be bad in itself, however, now when I retrieve the array of pointers via a `query` with `include`, my app crashes when I try to get the `object.parseClassName` with this message:

`[__NSDictionaryM parseClassName]: unrecognized selector sent to instance`

What gives?

**Comment by nlutsenko** [comment]
This is super strange and might be a bug in the new dashboard.
It fails to get the `parseClassName`, since the array contains maps (all keys and values) instead of just pointers, which have specific type and are decoded as Parse objects.
There were no changes in regards to how we treat arrays of pointers on saving/decoding end in the client SDK or backend, but there were changes in the dashboard.

@artooras, I would strongly recommend filing an issue on https://parse.com/help, since we are using FB Bug Tool for tracking dashboard issues.
Let me know if there is anything here that I've missed and feel free to reopen this issue if you think it's related to client in any way.

**Comment by artooras** [comment]
Sure, I'll file a bug report. Thanks.
