### ISSUE TITLE
Upload dsym file

### ISSUE THREAD

**Issue by rdaviduk** [ParsePlatform/Parse-SDK-iOS-OSX#754]
Hi, i need upload the dsym file to see where the app is crashing. i follow the tutorials on parse web but without results, its some tutorial updated to do that? i am working with osx "el capitan".
thanks

**Comment by richardjrossiii** [comment]
Hey guys, we've decided to deprecate our Crash Reporting product. We sent out an email to active users of Parse Crash Reporting last year. Here is a copy of that email:

--------

Update to Parse Crash Reporting

Hi there,

At Parse, we're always working to improve your developer experience. Last December, we launched Parse Crash Reporting with the goals of recognizing, tracking, and ultimately resolving crashes in your app.

In the time since, we've seen huge strides being made within the industry's native solutions. These native experiences have the advantage of being more tightly integrated into your build and release process, offering a more robust, streamlined, and frictionless development experience for you.

The Parse Crash Reporting tool is now being deprecated in favor of these great native solutions. We will continue supporting Parse Crash Reporting until March 1, 2016.

Here's how you can smoothly switch from Parse Crash Reporting to Apple or Google's offerings:

Apple Docs
Google Docs
We're constantly tackling new challenges to help you build better than ever before. Please reach out if you have any questions or concerns to community@parse.com.

The Parse Team
