### ISSUE TITLE
enableDataSharingWithApplicationGroupIdentifier("",containingApplicaiton: "") doesn't work

### ISSUE THREAD

**Issue by PMenotti17** [ParsePlatform/Parse-SDK-iOS-OSX#760]
hi, when i tried whrite this function appeared "unvaibale". Why?

**Comment by nlutsenko** [comment]
Hey @PMenotti17, that methods are unavailable on tvOS and watchOS 2, since there are no app extensions or built-in data sharing across applications.
Do you see it on iOS/OS X as well?

**Comment by PMenotti17** [comment]
hum. i understand. So, how i can import Parse in watchOS2?

**Comment by nlutsenko** [comment]
Just use it the same way you would use in any other iOS or OSX app.

**Comment by carmenalbu** [comment]
I do have an issue regarding this. 

So we have this tutorial from you to install Parse on our extensions:
http://blog.parse.com/announcements/introducing-local-data-sharing-for-apple-watch-and-app-extensions/

But. The method mentioned in the title is not available for watchOS. So the whole process was in vain, unfortunately.

Now my question is if this process is canceled, how can I synchronize my main app with my app watch? Because I need to get my current user, because it's a login based app, and I cannot do that anymore. 

I am little confused honestly. There is no documentation on this, and I really don't know how to get my current user. Or anything. It's not like "Just use it the same way you would in any other iOS app", because there are stuff that are not available on watchOS.. I cannot login my user through watchOS.

Can you help us on this one?

Thank you in advance,
Carmen Albu

**Comment by chavez-md** [comment]
I have the same issue as @carmenalbu.

There seems to be no documentation regarding how PFUser.currentUser() is shared when using watchOS 2. The documentation provided is for watchOS 1, and seems to no longer apply. 

Updated documentation for sharing information on watchOS 2 would be useful as this issue is indeed confusing. The only information regarding sharing is for watchOS 1 using enableDataSharingWithApplicationGroupIdentifier("",containingApplicaiton: ""), but is not available on watchOS 2 as mentioned above. 

Thanks

**Comment by jtbh89** [comment]
I'm in the same boat as @chavez-md. No idea how to get the currentUser in watchOS2 and no documentation that I can find.

**Comment by QB3L** [comment]
I realized this is closed but has anybody found a way to then get the current user with watchOS2?

I don't see any documentation anywhere regarding this.

**Comment by chavez-md** [comment]
@QB3L 
I did indeed get this working...

On the iPhone device you get the session token from the current logged in user through PFUser.currentUser().sessionToken. Now you must use watchConnectivity to send the session token to the watch from the iPhone device. Once you retrieve the session token on the watch use PFUser.become(sessionToken) which will then login the currentUser. This syntax is for swift. 

Hope this helps

**Comment by QB3L** [comment]
@chavez-md 
Thanks for that information. My app was simple enough that I could ignore the user completely and just ask for the info needed by the watch from the app. But this is awesome information for future reference as I hadn't looked at all at PFUser.become(sessionToken). Thanks again
