### ISSUE TITLE
Password reset does not reset password

### ISSUE THREAD

**Issue by bolaojewale** [ParsePlatform/Parse-SDK-iOS-OSX#761]
I have used the password reset functionality to reset the password to an account I am creating. For one particular user, the password reset functionality does not work. I can not even set the password for the user within Parse.

**Comment by nlutsenko** [comment]
Hey @bolaojewale, thanks for the report.
Looks like there are few separate issues you are experiencing here:
- Password reset doesn't send a verification email
- Inability to set a password for the user via dashboard

Since both of them sound to be disconnected from the SDK, could you file an issue on https://parse.com/help, since we are using FB Bug Tool to track both backend and dashboard issues?
Let me know if there is anything here that involves the SDK and I'll do my best to help you with that.
