### ISSUE TITLE
Array fields might contain NSDictionary instances instead of PFObject ones

### ISSUE THREAD

**Issue by yaalaa** [ParsePlatform/Parse-SDK-iOS-OSX#762]
iOS 9.2
Parse 1.12
Bolts 1.6.0

**Steps to reproduce:**
0. There are tables `A` & `B`. Table `A` has a field `list` of array type.
1. Create a record of `B`.
2. Create a record of `A`, add the `B` record to the `list` field.
3. Remove the `B` record.
_On the iOS client:_
4. Query `A` including `list`.

**Actual results:**
`list` field of array type contains **NSDictionary** instance.

**Expected results:**
On the cloud code I see pointer field comes null/undefined in similar circumstances.
Maybe to remove missed objects from the array too?
Or to make it of `PFObject` at least?

**Comment by nlutsenko** [comment]
Hey @yaalaa, thanks for the report.
We've seen few reports on this issue a while back and they were due to the dashboard saving incorrect values when manually editing the fields. It is related to the fact that Arrays of pointers are restricted to a specific format, and anything but that format won't be decoded into full `PFObject`s, but rather would fall back to `NSDictionary`.

Since you see the pointer fields come as null/undefined in CloudCode - this looks like a dashboard issue. Could you file a report on https://parse.com/help ("Contact Us" link in the middle of the page) - since we are using FB Bug Tool to track dashboard/backend issues.

Feel free to reopen the issue, if you still think there is something wrong in the iOS client.

**Comment by yaalaa** [comment]
Nikita do you think that the back-end sends NSDictionaries to the iOS device?:)

**Comment by nlutsenko** [comment]
`NSDictionary` is a client-side, ObjC-only representation of a JSON Object.
If for some reason dashboard is failing to save an array of pointers in a specific format, and rather saves them in a malformed way - it is going to surface as NSDictionary on the client, yes. :grin:

**Comment by yaalaa** [comment]
arrays are driving me mad today, it seems something very bad happened to parse back-end.

**Comment by yaalaa** [comment]
btw "contact us" link leads to facebook page where I get stuck on selecting "type of bug".
are the parse suffering some heavy flu?

**Comment by nlutsenko** [comment]
Not sure what you mean by "get stuck" - I've just went through the flow and it works great.
"Contact Us" -> "Select App, No Particular Platform" -> "Parse Dashboard" -> "Data Browser"

**Comment by yaalaa** [comment]
you're lucky. I've selected "REST or other" :)

**Comment by yaalaa** [comment]
btw here's what I've just got from support:
```
The format you are seeing for arrays is expected behavior. This is how it is designed on backend. The iOS SDK should be resolving these into Objects instead of a dictionary. You do not have to do anything in addition to it , to get your data. 

Hope this helps.

T.
```

the circle has closed. :)

**Comment by cashmash** [comment]
I am getting this issue now too, but no idea what caused it.
