### ISSUE TITLE
PFFacebookUtils has no member facebookLoginManager

### ISSUE THREAD

**Issue by AngeloGiurano** [ParsePlatform/Parse-SDK-iOS-OSX#770]
How can I access facebookLoginManager? I see it on the PFFacebookUtils class reference but cant access it.

<img width="882" alt="screenshot 2016-01-17 22 50 52" src="https://cloud.githubusercontent.com/assets/6850571/12380189/ea2b3d82-bd6c-11e5-9e09-32b8701abf95.png">

**Comment by nlutsenko** [comment]
Hey @AngeloGiurano, this sounds strange, as we explicitly import it in the latest version, as long as you compile for iOS (there is no `FBSDKLoginManager` on tvOS).

I would suggest trying to add `import FBSDKLoginKit` in your source file at the top.
Let me know if this helps, otherwise - could you post a code snippet that can reproduce the issue?

**Comment by AngeloGiurano** [comment]
Hi @nlutsenko, 

I'm using Parse for a quite a long time and yes this sounds strange for me aswell.

All I can say I've installed Parse from Cocoapods using:
    pod 'Facebook-iOS-SDK'
    pod 'Parse'
    pod 'ParseFacebookUtils'
    pod 'ParseUI'

In my AppDelegate I've initialized PFFacebookUtils by calling the method initializeFacebook()

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        Parse.enableLocalDatastore()
        // Initialize Parse.
        Parse.setApplicationId(parseID,
            clientKey: parseKey)
        
        // [Optional] Track statistics around application opens.
        PFAnalytics.trackAppOpenedWithLaunchOptions(launchOptions)
        PFFacebookUtils.initializeFacebook()


then in my LoginViewController Ive tried to call PFFacebookUtils.facebookLoginManager() and I get that there is no such a member

Also Ive tried to install yesterday ParseFacebookUtilsV4 but couldnt get it initialized it couldnt call the initializeFacebook() method is that normal?

Thanks a lot for your help

**Comment by nlutsenko** [comment]
Since you are using `ParseFacebookUtils` and not `ParseFacebookUtilsV4` - there is no `facebookLoginManager` on the old version (the difference between the two is that the latter is built for FBSDKv4).

`ParseFacebookUtilsV4.PFFacebookUtils` has a slightly different initialization format - `initializeFacebookWithApplicationLaunchOptions()`.
So in your method - it would something like
```swift
PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions(launchOptions)
```
I would suggest giving it a go.

Let me know how it goes and feel free to reopen this issue if the problem is still not resolved for you.
