### ISSUE TITLE
Authentication Error "Log in with Facebook" and normal sign in Code 0 Version 1.12.0

### ISSUE THREAD

**Issue by TheAncientMoonstone** [ParsePlatform/Parse-SDK-iOS-OSX#778]
I am not sure if this is either a client side, Parse Side or Facebook side error but every time time I try logging in with Facebook after the authorisation page I return with a "Login Failed Please try again" and receive the same error when I try logging in with a custom user name and password. Either way both respond with a code 0 response which does not seem to be documented anywhere.

I have checked multiple times on both my Facebook developer and Parse accounts and my .xcworkspace file that all API keys are the same.

I have attached a couple of screenshots.

![ios screenshot](https://cloud.githubusercontent.com/assets/13235485/12469299/cd4888a8-c03e-11e5-9c10-4bf5d7db3a48.jpg)
![xcworkspace screenshot](https://cloud.githubusercontent.com/assets/13235485/12469303/cd9f8a68-c03e-11e5-8bc9-142ef663b4a6.jpg)

**Comment by nlutsenko** [comment]
Hey @TheAncientMoonstone, thanks for the report.
Since the error is coming from the server and reference demo project works great at the current point - I would say it's either configuration issue or pure server-side issue.

Code 0 would mean that you have setup incorrect applicationId/clientKey when initializing the Parse SDK.
Any chance you can verify those and if it still doesn't work - could you paste a code snippet from your app delegate on how you setup Parse (feel free to strip away keys if neccessary)?

**Comment by TheAncientMoonstone** [comment]
Hey @nlutsenko Here is what how I set my AppDelegate
![appdelegate](https://cloud.githubusercontent.com/assets/13235485/12469659/c8f9c1e2-c041-11e5-8797-5d9e1ebe55f7.jpg)

**Comment by nlutsenko** [comment]
And I assume `@ApplicationId`, `@ClientKey` are valid, correct?

**Comment by TheAncientMoonstone** [comment]
Both are correct and valid

**Comment by nlutsenko** [comment]
Ok, perfect, that is helpful to diagnose the problem:
- Not 100% sure, but you might be missing any users in your Users class, which is why you can't login with username/password.
- For Facebook Auth, since you specified a specific App ID + Client Secret in Parse App Settings - make sure you have "Client Secret Embedded" enabled in the FB App Settings on developers.facebook.com
- You can also remove the FB AppId/ClientSecret just for testing purposes on Parse, which should be identical to the previous step, but I would discourage it, since you loose necessary security.

Let me know if any of these helped, if not - I have few more aces up my sleeve :grin:.

**Comment by TheAncientMoonstone** [comment]
Thanks for the help but I can't seem to find the "Client Secret Embedded" option that you were talking about. Can you please give me a rough pointer in where I can Find it?

**Comment by TheAncientMoonstone** [comment]
I have tested all of these and they still lead to the same error, what else can I do?

**Comment by nlutsenko** [comment]
One helpful thing might be using a [network debug tool](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool) to analyze which requests/response are being sent to the server.

**Comment by TheAncientMoonstone** [comment]
Hey @nlutsenko the network debug tool doesn't work for me as my project is written in swift. 
What other options do I have?

**Comment by TheAncientMoonstone** [comment]
Because my app is mainly written in swift I tried using the network debug tool that you linked before
<img width="1440" alt="screen shot 2016-01-24 at 10 02 58 pm" src="https://cloud.githubusercontent.com/assets/13235485/12535886/8f5b08f4-c2e6-11e5-8036-089f9bc9b10a.png">
<img width="1440" alt="screen shot 2016-01-24 at 10 03 20 pm" src="https://cloud.githubusercontent.com/assets/13235485/12535887/8fb1df44-c2e6-11e5-99ff-dfa1297ae537.png">

**Comment by nlutsenko** [comment]
@TheAncientMoonstone - to fix the problem remove `@` sign in front of every string under `Parse.setApplicationId( , clientKey:)`. You explicitly have wrong keys there - that's why login is failing.
