### ISSUE TITLE
why "log in" always fail?

### ISSUE THREAD

**Issue by saintPN** [ParsePlatform/Parse-SDK-iOS-OSX#780]
i'm including parse to my iOS app,i try to log in but it always says "invalid login parameters",i'm sure with   
username and password.
  and "sign up" works right,after sign up, i can get currentuse rightly.
  so, do you know why this happen? 
  thx advance.

**Comment by nlutsenko** [comment]
Hey @saintPN, the only reason why this might be happening is due to the username/password being incorrect. Any chance you have more details here?
We also have a wiki on how to enable network debugging [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool).
This might help analyze the network requests/responses sent to the server.

**Comment by saintPN** [comment]
i find out the problem，i make a stupid mistake of code，thx
