### ISSUE TITLE
How can I get all pin name in local datastore?

### ISSUE THREAD

**Issue by patpawasantanon** [ParsePlatform/Parse-SDK-iOS-OSX#785]
I use pinWithName with current location's geo point and I want to unpin them. How can I get all pin name of parse local datastore?

**Comment by nlutsenko** [comment]
Hey @patpawasantanon, unfortunately that is not the intended use case for pin names.
At the current stage, even though it would be easy to get all pin names, we are hesitant to add these, as it will limit changes to Local Datastore, like using a hash of pin names instead of storing them as raw strings.

If you explicitly want to be able to find pin names - I would recommend creating an offline-only object with a single column for array of strings, and pinning that one object, so your query is going to return only that object. Something close the following schema would be sufficient:
```
{
  "className" : "Pins"
  "names" : [ "yolo", "parse", "yarr" ]
}
```

Let me know if this works for you, or feel to reopen the issue if there is anything I might have missed.

**Comment by patpawasantanon** [comment]
So, how can I clear all local datastore without caring about pin name because I really don't know their pin name
