### ISSUE TITLE
fetchInBackgroundWithTarget:selector is deprecated

### ISSUE THREAD

**Issue by Sidheartx** [ParsePlatform/Parse-SDK-iOS-OSX#786]
<img width="1364" alt="screen shot 2016-01-24 at 4 50 12 pm" src="https://cloud.githubusercontent.com/assets/5414766/12535931/b4658290-c2ba-11e5-9afc-559e08fc6f2c.png">

It appears that parse has deprecated a few libraries and am unable to run the ParsePlatform AnyPic Project on my Xcode.I tried replacing it with PFObject but didn't work for me yet.Please help with clear guidelines

**Comment by nlutsenko** [comment]
Hey @Sidheartx, that method is indeed deprecated and this is intended behavior. 
Not sure why this would fail with an error though, since it should simply fail with a warning, since the method still exists and functions properly.
I'll take a look inside AnyPic repo and update accordingly, or you can take a shot at it and I'll be happy to review the pull request. The repo is located [here](https://github.com/parseplatform/anypic).
