### ISSUE TITLE
WatchOS - not supported?!?

### ISSUE THREAD

**Issue by carmenalbu** [ParsePlatform/Parse-SDK-iOS-OSX#787]
Hi. I have the latest version of Parse. And it seems I cannot use it in watch extension. There is a tag next to a very important method I should use in order to make it work on watchOS:

+ (void)enableDataSharingWithApplicationGroupIdentifier:(NSString *)groupIdentifier
                                  containingApplication:(NSString *)bundleIdentifier PF_WATCH_UNAVAILABLE PF_TV_UNAVAILABLE;

PF_WATCH_UNAVAILABLE. - if I remove it, of course I can use it, otherwise I get an error - the method is unavailable.

But I removed it, evidently, and I get nil from [PFUser currentUser];
 
I followed instructions from the link below in order to get it up and running. 
http://blog.parse.com/announcements/introducing-local-data-sharing-for-apple-watch-and-app-extensions/

Also added the little mentioned from the comments: [Parse enableLocalDatastore];

Still nothing. Does Parse still support watchOS? Should I continue to struggle? Because it was quite the ride to only get the framework installed in the extension.

Thank you in advance,
Carmen Albu

**Comment by nlutsenko** [comment]
watchOS 2 is explicitly supported. The blog post was written when watchOS 1 was just out, and the release of watchOS 2 this was supported and quite helpful.
The core difference between watchOS 1 and 2 is that app + extension is running purely on your watch.
The blog post and that method are still useful for App Extensions flow, since those are running on the same device (phone or a laptop).

For sharing data between watch and phone I recommend using built-in WatchConnectivity framework, and simply pass the currentUser.sessionToken to your watch.

**Comment by carmenalbu** [comment]
Then documentation should be updated as well. 

https://parse.com/docs/ios/guide#extensions

**Comment by nlutsenko** [comment]
Agreed, just updated in https://github.com/ParsePlatform/Docs/pull/318
