### ISSUE TITLE
Can I clear all data in local datastore?

### ISSUE THREAD

**Issue by patpawasantanon** [ParsePlatform/Parse-SDK-iOS-OSX#800]
Can I make local datastore empty without caring about any pin name that I created?

**Comment by nlutsenko** [comment]
Unfortunately - no, not via the public API.
The biggest reason for it - Local Datastore is being used internally inside the SDK for things like `currentUser` or `saveEventually`, so clearing it completely would mean that you'll run into weird consistencies.

This said, we probably can add an API to get all pin names and/or delete objects for all pins that are not private.
@grantland @richardjrossiii thoughts?

**Comment by patpawasantanon** [comment]
That would be great if you add an API to get all pin name.

**Comment by richardjrossiii** [comment]
Seeing as this is the second time we've had a request for fetching all pin names, I guess we can go that route. After all, LDSv2 is unlikely to happen at this point :(

**Comment by nlutsenko** [comment]
@patpawasantanon What is your use case for deleting all data from Local Datastore?
The reason for asking is trying to identify the best API for this use case:
- ability to delete all manually pinned objects
- ability to delete the entire local datastore
- ability to fetch all pin names

**Comment by patpawasantanon** [comment]
I was made a mistake by pinning objects with name with current geo coordinate. And now I want to unpin them but I don't know their name.

**Comment by nlutsenko** [comment]
That makes sense...
@patpawasantanon I would recommend taking a look at some of the internals of the client SDK here, specifically `PFPin` class. It is a client-side-only custom parse object that represents all of the pins.
Since the SDK is open source - you can easily expose the header for it and start using it.

Keep in mind that removing any pin that has `EventuallyPin` or `CurrentUser`/`CurrentInstallation` in it's name might lead to quite serious inconsistencies and should be avoided.

Will try my best to guide your way through this, while still to avoid adding a new public API for this use case.

**Comment by patpawasantanon** [comment]
now I can get all pin names. Thank you!

**Comment by nlutsenko** [comment]
Perfect! Glad I could help.
