### ISSUE TITLE
Parse Query execute simultaneously or sequentially ?

### ISSUE THREAD

**Issue by kirank-canwill** [ParsePlatform/Parse-SDK-iOS-OSX#803]
Hello 
I m calling many query at time like..
 [query1 findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
}];
 [query2 findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
} ];
 [query3 findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
}];
 [query4 findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
}];
 etc....
Then it will execute query1, query2, query3 query4?
OR query2, query1,query4, query3 Randomly?

Because while running such kind of query. I did not get any result for long time which  query I call from different page. That execute, after finishing previous query.

Thanks
Kiran

**Comment by nlutsenko** [comment]
Queries/network connections and such are actually meant to be fully concurrent, meaning they can and should execute at the same time.
Depending on multiple things, including server response time - you might get results in a different order for different queries, which is intentional.

I recommend you add all of these in a, say, `NSOperationQueue` or use Bolts Tasks to chain them together.
