### ISSUE TITLE
iOS Signing up problem with PFUser

### ISSUE THREAD

**Issue by techsd-repo** [ParsePlatform/Parse-SDK-iOS-OSX#835]
When I try to sign a user up with Parse I get the error: "Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}". I've done some research and have read that this was fixed in 1.9.1? 

Parse SDK version: 1.12.0
Development Platform: iOS

Thanks

**Comment by shobhz** [comment]
Yes. I too have been getting the same error.

**Comment by techsd-repo** [comment]
Code that throws the error: 
 ```
user.signUpInBackgroundWithBlock { (succeeded: Bool, error: NSError?) -> Void in
        if let error = error {
            print(error.description)
        } else {
        }
    }
```

**Comment by nlutsenko** [comment]
Hey guys, let's debug this together:
- Are you using parse.com or self-hosted parse server?
- If the latter - could you run it with `VERBOSE=1` and paste the network requests here?
- If the former - could you instrument your app on the client with network debugging specified [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool) and paste the output of the request/response here?

That error suggests that you actually are getting malformed JSON back, meaning that something went wrong on the server and I am extremely curious on what and where.

**Comment by techsd-repo** [comment]
I'm using Parse Server, but how would I run the app in Verbose mode, is it
in Preprocessing Macros?

**Comment by mitchellporter** [comment]
@techsd-repo In your iOS app's app delegate class file, or wherever you initialize the Parse iOS SDK, add the following line of code: `Parse.setLogLevel(.Info)`

That's in Swift, but you should have no problems figuring out an objc translation. I'm not sure why @nlutsenko called it "verbose" instead of "Info", but it's probably because many other SDK's refer to their most detailed log level as verbose and he's used to saying that a lot :)

**Comment by nlutsenko** [comment]
@mitchellporter, haha, that's so awesome.

I actually literally meant verbose mode in Parse Server.
It's purely an environment variable, and it roughly depends on how you are starting/running your server, but say if you are running via `bin` script - it would be something like `VERBOSE=1 npm start ...`.

The latter solution that I specified above (instrumenting the app on the client with network debug calls) actually would work as well in this case, though the important information is contained in the server logs with verbose mode though.

Also, few more questions:
- Does other functionality work when calling from iOS SDK against the same server?
- Can you try using a REST API to sign up? The request is best described [here](https://parse.com/docs/rest/guide#users-signing-up), but something like this would work great:
```
curl -X POST \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "Content-Type: application/json" \
  -d '{"username":"yarr","password":"yolo"}' \
  http://${YOUR_SERVER_URL}/users
```

If they don't - then my wild guess would be that you got the serverURL wrong and it's trying to access a URL that `404`s back to you with malformed JSON. Since default express 404 page actually doesn't produce JSON - it surfaces here as that error.

**Comment by mitchellporter** [comment]
@nlutsenko Today I learned about verbose mode for Parse Server :)

**Comment by techsd-repo** [comment]
I **cannot** use the REST API to sign up. I get the error: "301: Moved Permanently". That's probably why I got the JSON error.

**Comment by nlutsenko** [comment]
Yup, sounds like my theory is correct. I recommend double checking path where you mounted the server and the URL. If you specify them here (even mangled) - I'll be able to give you the full configuration string that you want.

**Comment by techsd-repo** [comment]
Server URL: "http://www.**************.herokuapp.com/parse"
^ not deployed inside another directory on the instance

**Comment by nlutsenko** [comment]
That actually looks correct, but what happens if you remove `www.`?

**Comment by techsd-repo** [comment]
That appears to work. Thanks :)
