### ISSUE TITLE
saveInBackground not being called sometimes

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/Parse-SDK-iOS-OSX#848]
Sometimes I've noticed that saving two different PFObjects in the background does not work properly, so what I've done to fix this is save the first, and in a completion block then save the second, but I'd prefer to save them both at the same time. This only started happening with parse-server. 

`incomingRequest.saveInBackgroundWithBlock { (success: Bool, error: NSError?) -> Void in
    let myFriends = PFUser.currentUser()!.relationForKey("friends")
    myFriends.addObject(fromUser)
    PFUser.currentUser()!.saveInBackground()`

Before I was able to do this:
`incomingRequest.saveInBackground()` and have everything else work properly.

**Comment by nlutsenko** [comment]
Sounds very strange, and definitely not expected. Let's debug this together.
Few questions, so we can start investigating:
- Does the above calls work against Parse.com?
- Could you instrument your app with Network Debug Tool from [this guide](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool) and paste the output here?

Let's see where can we get from here and then will look into the output to verify that it's correctly sent to the server, and then - if the server doesn't reply properly - we'll open an issue there and fix it for everyone, otherwise - fix it here.
