### ISSUE TITLE
How to prevent Parse from saving ParseObject children's

### ISSUE THREAD

**Issue by genius50** [ParsePlatform/Parse-SDK-iOS-OSX#851]
I'm facing a big issue, trying to update a PFObject that has a User as a pointer, I can't do that since I'm getting the Error 

```
object.incrementKey("Likes", byAmount: -1)
object.removeObject((PFUser.currentUser()?.objectId)!, forKey: "LikesUsers")
object.saveEventually() 
```

> User cannot be saved unless they have been authenticated via logIn or signUp

Even I didn't change the User object when retrieving the parent, so is there any way to prevent the Parse from saving the Parse object children

**Comment by nlutsenko** [comment]
Hey @genius50, not sure whether the problem is that serious.
Let me ask you few questions, so we can debug this together:
- What does your schema look like for `object`, specifically - I am interested in type of `LikesUsers`.
- Is `PFUser.currentUser()` logged in? 

Be aware that you explicitly can't reference a currentUser that is not authenticated as a pointer in any object.

**Comment by genius50** [comment]
`LikesUsers` is an Array of String
`CurrentUser()` is already logged in
the problem comes from `object` which has a pointer to another user
