### ISSUE TITLE
Xcode 7.3 Swift : Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'

### ISSUE THREAD

**Issue by flessard** [ParsePlatform/Parse-SDK-iOS-OSX#865]
I got this error :  Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'

And this error :  Could not build module 'FBSDKCoreKit'

ParseFacebookUtilsV4 is compatible whit Xcode 7.3 Swift ?

**Comment by nlutsenko** [comment]
Hey @flessard, this is not related to ParseFacebookUtilsV4, but rather to any CocoaPod that depends on FBSDK. We have an issue tracked in https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/2 for quite a while. Looks like this is a double-ended thing caused by CocoaPods and FBSDK combined.
There is also a FB Bug open for it that could be useful to track: https://developers.facebook.com/bugs/1573036833024413/
