### ISSUE TITLE
Invalid Function when Cloud Code function exists

### ISSUE THREAD

**Issue by techsd-repo** [ParsePlatform/Parse-SDK-iOS-OSX#872]
Whenever I call a cloud code function inside my app, it returns the error: Invalid Function. I've tripe-checked the function name and have verified that it exists in code. I just about to switch to Firebase because of the amount of issues I've been having (I rather not switch because it's time consuming).

Parse Server (Heroku) : 2.2.0

Thanks.

**Comment by nlutsenko** [comment]
Hey @techsd-repo, sounds very strange, as we don't have any other reports around this and it's a very core functionality.
I would recommend filing an issue on [Parse Server GitHub repo](https://github.com/parseplatform/parse-server), since we are using this one for tracking client-side issues only.

Let me know if you think this is client-side related or if there is anything I might have missed.

**Comment by THEDOWNCOUNTRY** [comment]
I have this same problem
