### ISSUE TITLE
How to prevent Parse from saving PFObject children's?

### ISSUE THREAD

**Issue by genius50** [ParsePlatform/Parse-SDK-iOS-OSX#875]
I'm facing a very common issue with Parse and iOS.

I have a class POST with the following structure:

> text(String)
> Image (PFFile)
> LikesUsers (Array of String)
> LikesCount (Int)
> From (Pointer to User who posted it)

Any user (Logged in) can like a post. I'm just incrementing the likes **LikesCount** and the add Objectid of the user to the array of **LikesUsers**

The user2 likes user1's post.

```
PostObject.incrementKey("Likes")
PostObject.addObject((PFUser.currentUser()?.objectId)!, forKey: "LikesUsers")
PostObject.saveEventually()
```

The issue is here. Parse can't save the PostObject as long as it has a pointer to another user : User1 (the user who posted the post). 

> User cannot be saved unless they have been authenticated via logIn or signUp

So I would like to know how to prevent Parse from saving the PFObject children (Pointer to the user). even I went through all my code and I'm sure I'm not trying to make any changes on this User. I don't know why it's dirty.

**Comment by nlutsenko** [comment]
Hey @genius50, sorry it took a while to get back to you here.
Unfortunately, there isn't a way currently to prevent saving a children object currently.

Though, it sounds absolutely like it should work just as fine in your case, so let's debug this together.
Since you are saving a users `objectId` and not the object itself - it shouldn't save a children here, but what could happen is that `user2` is not yet fully authenticated.

If you are integrating via CocoaPods or have source code locally you can place a breakpoint on [this line](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/PFObject.m#L1168) while debugging and confirm whether you have a dirty change on your user object (this will trigger for every object, but you can filter that further manually).

Finally, what would help tremendously in identifying the root cause and fixing it - a good repro project or a code snippet.

Let me know how it goes and we will find the source of the problem together.

**Comment by genius50** [comment]
Hello there !

Thanks for your response, I've almost Identified the problem, in my code I'm trying to save the Users locally using **pinInBackgroundWithName("LocalContacts")**

So here where the problem comes from ! I'm just keeping the users info on the LocalStore, I'm making some changes on it and saving them back locally using **pinInBackgroundWithName("LocalContacts")**

But when trying to retrieve the posts, with the Users, and Trying to like a post, it takes the data from the User who are saved locally. How to resolve that, do you have any idea ?

**Comment by nlutsenko** [comment]
Thanks for clarifying.
Unfortunately, we don't have a mechanism in place to disable saving child objects, meaning that if you don't want to save these objects to the server - you would probably want to convert them to plain JSON Objects (aka dictionaries/arrays/strings/numbers) and use that for saving.

I would advise against using `PFUser` class in general for offline local-only users, since the intended use case is to use it with server-side authentication. You would benefit from using a plain subclass of a PFObject in this case.

Let me know if this solution works for you.

**Comment by genius50** [comment]
Thanks,

Finally I've managed to avoid the problem. I just made things different, I had to keep the Parse Users as they used to be on the server, without any local change, and everything work just fine.
