### ISSUE TITLE
IOS SDK calls for a POST

### ISSUE THREAD

**Issue by ajamaica** [ParsePlatform/Parse-SDK-iOS-OSX#882]
Testing config the IOS client calls for POST and it returns a 404. The REST api works good with get. 

167.58.124.130 - - [01/Apr/2016:14:16:07 +0000] "POST /parse/config HTTP/1.1" 404 26 "-" "curl/7.43.0"
167.58.124.130 - - [01/Apr/2016:14:16:10 +0000] "GET /parse/config HTTP/1.1" 200 2656 "-" "curl/7.43.0"

**Comment by nlutsenko** [comment]
We actually are never calling `POST` from an iOS SDK on config, only `GET` and have a capability to use `PUT`. You can instrument your app with our [network profiling tool](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool) and see all the network requests that we are making.

This said, even using `curl` will fail to `POST` to `/config` since there is no such endpoint.
I can help you further, but would need more information on what you are trying to achieve.
