### ISSUE TITLE
reset_password invalid link in iOS Safari only

### ISSUE THREAD

**Issue by Jinoooo** [ParsePlatform/Parse-SDK-iOS-OSX#891]
Using iOS SDK, a reset password request send the email with the correct token as part of the url provided in the email.
Clicking on the email link will work perfectly on desktop.  However, when I clink the url on iPhone iOS safari 9.0, it says invalid link.
I compared the url in iOS safari vs safari in my macbook, and noticed in iOS safari the token string (and everything else) has been converted to lowercase, and that maybe explains the reason.
Anybody has faced this issue?
How can it be fixed?

**Comment by nlutsenko** [comment]
Hey @Jinoooo, thanks for the report.
This is definitely a server-side issue, since the verification email is generated and sent by the server, where the client only requests the email to be sent for a given email.

I would recommend reporting this issue on Parse Server repo [here](https://github.com/parseplatform/parse-server) or in case you are still using Parse.com - [here](https://parse.com/help).
