### ISSUE TITLE
How to handle Brute Force login attempts?

### ISSUE THREAD

**Issue by skimgosu** [ParsePlatform/Parse-SDK-iOS-OSX#892]
I am trying to have more control over how logins work and are handled.

Is there anyway to throttle the login attempts?

**Comment by nlutsenko** [comment]
Hey @skimgosu, that's a great question!

There is no way to control the throttle parse.com, but in case of Parse Server - you can plug in any throttling mechanism as a middleware for your express app. For example, [express-brute](https://www.npmjs.com/package/express-brute) is easy to setup and gives you an ability to rate limit a specific endpoint by the total count a day from a specific IP or plug in your own logic.

Let me know if this helps, and feel free to reopen this issue. Or even better - open this on Parse Server [repo](https://github.com/parseplatform/parse-server), since this is closer related to it.

**Comment by skimgosu** [comment]
xpress-brute looks great! Thanks @nlutsenko
