### ISSUE TITLE
getObjectInBackgroundWithId with nil ObjectId returns an object

### ISSUE THREAD

**Issue by rmaqueda** [ParsePlatform/Parse-SDK-iOS-OSX#898]
SDK Versión: 1.13.0

Hi all,

I think I found a mistake in method getObjectInBackgroundWithId. Its behaviour is strange when I send a nil value on ObjectId to this query: it returns the last object from the table!
This behaviour is different with bolts call: returns nil (I think that it's the correct response).

Example:

```
PFQuery *query = [MOLDocument query];
query.cachePolicy = kPFCachePolicyCacheThenNetwork;
[query getObjectInBackgroundWithId:nil block:^(PFObject * _Nullable object, NSError * _Nullable error) {
   NSLog(@"The return objectId: %@", object.objectId);
}];



The return objectId: WiAXFAWrJM
```

Example with bolts:
```
PFQuery *query = [MOLDocument query];
[[query getObjectInBackgroundWithId:nil] continueWithBlock:^id _Nullable(BFTask * _Nonnull task) {
   PFObject *object = task.result;
   NSLog(@"The return objectId: %@", object.objectId);
   return task;
}];



The return objectId: (null)
```

¿What do you think? Thanks!!

**Comment by nlutsenko** [comment]
@rmaqueda, those queries above look different... 
Can you verify this behavior if you remove `cachePolicy` from the above code snippet?
Otherwise, what might be happening is that it hits cache first and then hits network.
This won't work without a block callback, because you can have only a single result on any given task.
