### ISSUE TITLE
retrieve PFFile closes connection

### ISSUE THREAD

**Issue by sbauch** [ParsePlatform/Parse-SDK-iOS-OSX#900]
I'm not sure what side of the SDK / parse-server project this falls on, apologies if posting twice was the wrong thing to do! https://github.com/ParsePlatform/parse-server/issues/1509

I'm able to save PFFiles just fine (I'm working with videos on iOS), but when the app tries to retrieve the file, the parse-server I'm running on heroku throws an H27 error, described by heroku as - "This error will be logged if the client socket was closed either in the middle of the request or before a response could be returned."

Since I'm able to retrieve the movie files via the same URL using my desktop browser, I am starting to think this is an issue in the client SDK.

**Comment by nlutsenko** [comment]
Hey @sbauch,

Is there any chance you can post here or send me the file link for this video?
I can try debugging this deeper on the client, but since this is the first report of this kind - not sure there is a lot of things we could do here.

Also, since `MPMoviePlayerViewController` also fails to load this video, I am skeptical about the fact that this is a client-side issue.

**Comment by sbauch** [comment]
@nlutsenko sure I'm happy to post some vid links here.

Granted I've been playing with some things to try and get it going. The URLs are what I get from the SDK for the URL of the file, which is odd because I'm pointing at https, and all of these are http.

Here's an URL to a file that was saved with a `video/mp4` content type. I can open this on desktop chrome, not on ios safari. 

http://klaw-server.herokuapp.com/parse/files/wqoJH3e0gxuMLSFODlBJgaE5w0cAhepZvHIgmXNd/33f5aa74508ed74a1e9de8428b713eb0_movie.mp4

here's a slightly larger .mov file, this was chosen from the camera roll on an iPhone
http://klaw-server.herokuapp.com/parse/files/wqoJH3e0gxuMLSFODlBJgaE5w0cAhepZvHIgmXNd/8cbf384f7f9ef9d4afa1574bedc722a9_movie.mov

and lastly, this is kind of odd and I am not totally sure what's causing, but some videos are saved to s3 with a .bin extension, so I've also been trying to specify various content types in the app to get this right. This downloads fine with chrome, but they can't be opened really.

http://klaw-server.herokuapp.com/parse/files/wqoJH3e0gxuMLSFODlBJgaE5w0cAhepZvHIgmXNd/aee1e01673bbd0ac1227b202ce115a38_movie.bin

this is part of a migration project from parse.com btw. This was definitely all working prior to that switch, and I want to say it was working as of recently for me, but I've been a little blind on the project to pinpoint when this feature actually stopped working for me.

**Comment by nlutsenko** [comment]
After doing some debugging - it looks like indeed it's failing to retrieve these files.
Content-type is reported properly on these, so it's not that piece.
Let me ask you few questions here:
- Which file adapter are you using for storing these files?
- Have you tried any other file adapter?

I believe Safari/QuickTime actually fails to load these files due to Heroku HTTP routing.
Since parse.com is using S3 for file storage - I highly recommend using S3 for all your file needs.
The official supported adapter lives [here](https://github.com/parse-server-modules/parse-server-s3-adapter) together with documentation on how to set up S3 [here](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters).

If you are indeed using S3 adapter - I would recommend changing the way you are serving files to 302 to S3 instead of being proxied via Heroku, as it should be waay faster and we can eliminate any possibility of Heroku networking getting in the way here.
The relevant function to change, in this case, is [here](https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/FilesRouter.js#L35). You would need to get the `getFileLocation()` from an adapter instead of going for raw binary data.

**Comment by sbauch** [comment]
I'm using the S3 adapter, haven't tried other adapters. Images are working perfectly with my current setup, just videos that are giving trouble, so I'd like to stick with s3.

I was under the impression that the `directAccess` config for a file adapter was in fact doing that 302 but I suppose I misunderstood.

I've forked the parse-server project and am trying to implement your suggestions, but I'm having a lot of trouble with the build process, node/npm and pointing to my forked version. I don't think this is the appropriate place for those topics.

**Comment by sbauch** [comment]
Ok this is resolved. Once I added en ENV var for bucket prefix and disabled heroku npm caching, files are being served directly from s3 and can be opened by the app. thanks @nlutsenko! I think I'll also make note on the server side since that's where this seems to be an issue for me.
