### ISSUE TITLE
PFFieldOperation Crash More Prominent

### ISSUE THREAD

**Issue by acegreen** [ParsePlatform/Parse-SDK-iOS-OSX#908]
Hey, 

I'm noticing a more frequent crash. I'll try to include as much info as I can gather. **This has happened in 13 out of the past 30 days**

<img width="972" alt="screen shot 2016-04-24 at 4 36 11 pm" src="https://cloud.githubusercontent.com/assets/10794609/14770257/ec261524-0a3a-11e6-91dc-334d51eb4bbc.png">
<img width="924" alt="screen shot 2016-04-24 at 4 36 52 pm" src="https://cloud.githubusercontent.com/assets/10794609/14770256/ec247a02-0a3a-11e6-99dd-d105c4fe38fd.png">
<img width="935" alt="screen shot 2016-04-24 at 4 37 14 pm" src="https://cloud.githubusercontent.com/assets/10794609/14770255/ec23ea06-0a3a-11e6-9ca9-2c5d598932f9.png">

**Comment by nlutsenko** [comment]
Hey @acegreen,

This happens due to the fact that you are trying to apply a `remove` operation on an object that has an operation that is different from `Set`/`Remove` (most likely an `Add`) operation pending for the same key.
I would recommend structuring your code in a way that will enforce the object to be saved in between these operations, which will remove the crash.

We had few discussions on how we could provide both `Add` and `Remove` support for a given key without requiring round-trips to the server and back, but this most likely only going to happen in the world of Parse Server.

Let me know if this helps in any way or you think there might be something else involved here.

**Comment by acegreen** [comment]
I'm still experiencing this crash and the above description doesn't seem to apply here. Can we reopen this.

Take a look at the screenshots above, the last function called on my side is the **registerUserChoice()**

```
    class func registerUserChoice(chart: Chart, and object: PFObject?, with choice: Constants.UserChoices) {
        
        guard (PFUser.currentUser() != nil) else { return }
        
        var removeFromKey: String!
        var addToKey: String!
        
        switch choice {
            
        case .LONG:
            removeFromKey = Constants.UserChoices.SHORT.key()
            addToKey = Constants.UserChoices.LONG.key()
            
        case .SHORT:
            removeFromKey = Constants.UserChoices.LONG.key()
            addToKey = Constants.UserChoices.SHORT.key()
            
        default:
            break
        }
        
        if let object = object {
            
            object.removeObject(PFUser.currentUser()!, forKey: removeFromKey)
            
            if object.objectForKey(addToKey) != nil {
                
                object.addUniqueObject(PFUser.currentUser()!, forKey: addToKey)
                
            } else {
                
                object.setObject([PFUser.currentUser()!], forKey: addToKey)
            }
            
            object.saveEventually({ (success, error) -> Void in
            })
        }
        
        print("\(choice)", object)
        print("Chart:", chart.searchDescription)
        
        saveIntoCoreData(chart, userChoice: choice)
        
    } 
```

I don't perform two operation on the same object

**Comment by acegreen** [comment]
@nlutsenko any additional thoughts on this? code snippet above
