### ISSUE TITLE
+[PFConfig currentConfig] warning on `long-running operation is being executed on the main thread`

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/Parse-SDK-iOS-OSX#91]
Hey Parsers!

In my app, I'm calling `+[PFConfig currentConfig]`, expecting to get the currentConfig. I received the warning `long-running operation is being executed on the main thread`, and when adding the symbolic breakpoint, I got the following:

![screen shot 2015-08-23 at 11 31 23 am](https://cloud.githubusercontent.com/assets/1164565/9427512/888b8092-498a-11e5-8beb-aee38d8a59c5.png)

What is strange is, that I call `getConfigInBackgroundWithBlock`, and in the completion block, other method tries to access `currentConfig`, triggering the warning. 

My question is: is it ok to ask for the `currentConfig` in the main thread, right? If so, why am I getting the warning? If not, what am I doing wrong?

**Comment by nlutsenko** [comment]
Yes, it's absolutely fine, this warning is actually coming from Bolts.framework which warns you that you are executing `PFConfig.currentConfig()` on the main thread. This operation is basically free if you currentConfig was loaded into memory, otherwise it might be slightly expensive (based on the size of your config).

It's strange that you see this warning, since it should have been fixed in v1.8.0.
Any chance you can confirm the version of the SDK that you are using?

**Comment by natanrolnik** [comment]
Oh, good to hear.
I'm using the one earlier than 1.8.0, due to the localization bug in 1.8.0. So I'll just update to 1.8.0 using pointing to Master here in my Podfile (or when is 1.8.1 being released?)

**Comment by natanrolnik** [comment]
BTW, is there any place (or twitter feed) where we can be notified of new SDK versions?

**Comment by nlutsenko** [comment]
You can start watching the repo on GitHub - it will notify you (I hope).
Our official Twitter is `@parseit`, but so far we didn't announce new releases, but there have been talks to actually do it, so I think it's definetly coming now.

**Comment by natanrolnik** [comment]
I guess that watching will notify me about more than only releases, no?
That will be great to have on Twitter, even if in a new Twitter account just for that.
