### ISSUE TITLE
SDK breaks signature in Swift project

### ISSUE THREAD

**Issue by alexbat98** [ParsePlatform/Parse-SDK-iOS-OSX#92]
I added Parse SDK to my existing iOS project. Everything was OK. Then I added ParseCrashReporting. Now I can't start my app on a real device. Xcode fails with the following message: "App Installation Failed, The application does not have a valid signature". Tried cleaning project and recreating provisioning profile. Nothing helps.

**Comment by nlutsenko** [comment]
Hey @alexbat98,

Tested right now running ParseCrashReporting both on the simulator and building and running on the device - everything works like a charm, so I suspect there is something about your project configuration specifically that blocks it.

Can you share a more concrete example or a repro project? This would help us in identifying the root cause and fixing it for you in a fast manner.

**Comment by alexbat98** [comment]
@nlutsenko I can't share my sources here. So, I emailed you with an address provided in your GitHub account. Thanks for help.

**Comment by nlutsenko** [comment]
Just got it, thanks. I'll take a look in depth tomorrow and post here.



On Sun, Aug 23, 2015 at 11:35 PM -0700, "Alexander" <notifications@github.com<mailto:notifications@github.com>> wrote:


@nlutsenko<https://github.com/nlutsenko> I can't share my sources here. So, I emailed you with an address provided in your GitHub account. Thanks for help.

**Comment by alexbat98** [comment]
Managed on my own. I deleted my project and cloned it from git repo to another directory (reverting changes doesn't work). Then I followed instructions on parse.com. For some reason, first time I did it Parse and Bolts appeared in the Embedded binaries sections. That breaks the project. Now they are in the Linked Binaries section. Everything works like a charm.
