### ISSUE TITLE
'exception' is deprecated: `BFTask` exception handling is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by dkbuckley** [ParsePlatform/Parse-SDK-iOS-OSX#965]
When I run my project I get 45 of these issues. What does it mean and how can I remove? 

> 'exception' is deprecated: `BFTask` exception handling is deprecated and will be removed in a future release.

**Comment by brianyyz** [comment]
"Deprecated" is usually a warning from the software authors that a method or class has been superseded by a better or safer implementation and that the deprecated class or method may be removed in a future release. In short, it is a warning to update your app. See Wikipedia or SO for fuller discussion.

**Comment by nlutsenko** [comment]
This is intentionally deprecated as of Bolts-ObjC 1.8.0.
The next version of Parse SDK is going to fix all violations of this, as per #956

**Comment by DanGTZ** [comment]
I'm currently using Parse SDK 1.14.2 and Bolts 1.8.4 and I can see that PFObject.saveInBackground() itself can return a faulted BFTask that has only its exception field set (with error field not set).
So this forces us to use task exception to get the description of the problem, and to keep the warning in our project.
@nlutsenko : the exception I get is "Tried to save an object with a pointer to a new, unsaved object.", that is thrown from resolveLocalId method in PFObject. Does this is the expected behaviour from Parse? Or is this a bug from Bolts that should catch the exception and return an error instead?

**Comment by JEKos** [comment]
This deprecated warning still exist on latest 1.14.4

**Comment by flovilmart** [comment]
In which case does it return an exception? Can you point out the code that triggers it?

**Comment by JEKos** [comment]
I change the 'exception' to 'error' and now it's ok. I can't find it right now where was it

**Comment by bhanubirani** [comment]
Not sure if this is fixed.. I still get the same exception which doesn't allow my app to launch.

```
2017-07-26 08:24:56.269016+0530 Aiko[2752:300124] [Bolts] Warning: `BFTask` caught an exception in the continuation block. This behavior is discouraged and will be removed in a future release. Caught Exception: Cannot do a comparison query for type: (null)
```

Any help on how do I fix it? or any quick-fix?
